apiVersion: apps/v1
kind: Deployment
metadata:
  name: tubearchivist
  namespace: tubearchivist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tubearchivist
  template:
    metadata:
      labels:
        app: tubearchivist
        vpn-gateway: "true"
    spec:
      containers:
        - name: tubearchivist
          image: bbilly1/tubearchivist:v0.5.10
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: ES_URL
              value: http://archivist-es.tubearchivist.svc.cluster.local:9200
            - name: REDIS_CON
              value: redis://archivist-redis.tubearchivist.svc.cluster.local:6379
            - name: TA_HOST
              value: https://tubearchivist.net.ecksd.ee
            - name: TZ
              value: UTC
            - name: TA_USERNAME
              value: tubearchivist
            - name: TA_PASSWORD
              value: tubearchivist
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tubearchivist
                  key: ELASTIC_PASSWORD
          volumeMounts:
            - name: youtube
              mountPath: /youtube
            - name: cache
              mountPath: /cache
          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: tubearchivist.net.ecksd.ee
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: tubearchivist.net.ecksd.ee
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            requests:
              memory: 768Mi
              cpu: 250m
            limits:
              memory: 1536Mi
              cpu: "2"
      volumes:
        - name: youtube
          persistentVolumeClaim:
            claimName: tubearchivist-youtube
        - name: cache
          persistentVolumeClaim:
            claimName: tubearchivist-cache
