apiVersion: v1
kind: PersistentVolume
metadata:
  name: tubearchivist-youtube-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: nas.net.ecksd.ee
    path: /volume1/malachit/media/youtube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-youtube
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: tubearchivist-youtube-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-cache
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-redis
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-es
  namespace: tubearchivist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 1Gi
