apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: forward-auth-qbittorrent
  namespace: authentik
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: qbittorrent
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: qbittorrent
  to:
    - group: ""
      kind: Service
      name: authentik-server
