apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - forward-auth-sonarr.yaml
  - forward-auth-radarr.yaml
  - forward-auth-bazarr.yaml
  - forward-auth-prowlarr.yaml
  - forward-auth-tubearchivist.yaml
  - forward-auth-paperless-ngx.yaml
  - forward-auth-qbittorrent.yaml
  - forward-auth-spoolman.yaml
  - forward-auth-zilean.yaml
