apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: XD Net
    language: en
    headerStyle: boxed
    hideVersion: true

    layout:
      Media:
        style: row
        columns: 3
      Identity:
        style: row
        columns: 3
      Infra:
        style: row
        columns: 3

  bookmarks.yaml: ""

  services.yaml: |
    - Media:
        - Plex:
            href: https://plex.net.ecksd.ee
            description: Media server

    - Infra:
        - NGINX:
            description: Example service

  widgets.yaml: |
    - search:
        provider: google
        target: _blank

  kubernetes.yaml: |
    mode: cluster

    # Automatic service discovery sources
    ingress: false
    traefik: false
    gateway: true

  docker.yaml: ""

  proxmox.yaml: |
    ---
    # pve:
    # url: https://proxmox.host.or.ip:8006
    # token: username@pam!Token ID
    # secret: secret

  custom.css: |

  custom.js: |


