apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: XD Net
    language: en
    headerStyle: clean
    hideVersion: true
    statusStyle: dot
    maxGroupColumns: 4

    layout:
      Media:
        icon: mdi-play-network-outline
        style: row
        columns: 3
      Arr!:
        icon: mdi-pirate
      Management:
        icon: mdi-tools
      Data storage:
        icon: mdi-database-outline
      Misc:
        icon: mdi-dots-horizontal

  bookmarks.yaml: ""

  services.yaml: |
    - Arr!:
        - Upcoming:
            description: TV show episodes
            weight: -1
            widget:
              type: calendar
              view: agenda
              maxEvents: 7
              integrations:
                - type: sonarr
                  service_group: Media
                  service_name: Sonarr
                  color: teal
                  params:
                    unmonitored: true
    - Management:
        - UniFi:
            href: https://unifi.ui.com
            description: UniFi controller
            weight: 10
            icon: si-ubiquiti
            siteMonitor: https://unifi.net.ecksd.ee
            statusStyle: ""
        - Pangolin:
            description: Remote access edge
            weight: 35
            href: "{{HOMEPAGE_VAR_PANGOLIN_DASHBOARD_URL}}"
            icon: mdi-shield-link-variant-outline
            widget:
              type: pangolin
              url: "{{HOMEPAGE_VAR_PANGOLIN_API_URL}}"
              key: "{{HOMEPAGE_VAR_PANGOLIN_API_KEY}}"
              org: "{{HOMEPAGE_VAR_PANGOLIN_ORG}}"
              fields: ["sites", "resources", "targets", "traffic"]
        - DSM:
            description: Synology UI
            weight: 45
            href: https://nas.net.ecksd.ee/
            icon: si-synology
            siteMonitor: https://nas.net.ecksd.ee
            statusStyle: ""
            widget:
              type: diskstation
              url: https://nas.net.ecksd.ee/
              username: "{{HOMEPAGE_VAR_DSM_USERNAME}}"
              password: "{{HOMEPAGE_VAR_DSM_PASSWORD}}"
              volume: volume_1

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: cluster
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  kubernetes.yaml: |
    mode: cluster

    # Automatic service discovery sources
    ingress: false
    traefik: false
    gateway: true

  docker.yaml: ""

  proxmox.yaml: ""

  custom.css: ""

  custom.js: ""
