apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-gateway-pod-gateway-main
  namespace: vpn-gateway
spec:
  template:
    spec:
      volumes:
        - name: gluetun-iptables
          configMap:
            name: vpn-gateway-gluetun-iptables
      containers:
        - name: gluetun
          volumeMounts:
            - name: gluetun-iptables
              mountPath: /iptables
              readOnly: true
