apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitmagnet

resources:
  - namespace.yaml
  - pvc-config.yaml
  - postgres.yaml
  - backup.yaml
  - httproute.yaml
  - private-resource-pangolin.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
    releaseName: bitmagnet
    namespace: bitmagnet
    valuesFile: values.yaml
