apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracearr

resources:
  - namespace.yaml
  - httproute.yaml
  - image-catalog.yaml
  - postgres.yaml

helmGlobals:
  chartHome: vendor/tracearr-0.2.2

helmCharts:
  - name: tracearr
    releaseName: tracearr
    namespace: tracearr
    version: 0.2.2
    valuesFile: values.yaml
