# NFS ingest at /volume1/ingest/downloads; separate PV per namespace.
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads-pv
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: nas.net.ecksd.ee
    path: /volume1/ingest/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  volumeName: radarr-downloads-pv
  storageClassName: ""
