apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml
  - nfs-library.yaml
  - httproute.yaml
  - postgres.yaml
  - backup.yaml

helmCharts:
  - name: immich
    repo: oci://ghcr.io/immich-app/immich-charts
    version: 0.12.0
    releaseName: immich
    namespace: immich
    valuesFile: values.yaml
