apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bambuddy

resources:
  - namespace.yaml
  - pvc.yaml
  - httproute.yaml
  - macvlan-network.yaml
  - bambu-studio.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
    releaseName: bambuddy
    namespace: bambuddy
    valuesFile: values.yaml
