apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-db
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  storage:
    storageClass: local-path
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi
  bootstrap:
    initdb:
      database: mealie
      owner: mealie
      secret:
        name: mealie-db
