apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflux

resources:
  - namespace.yaml
  - postgres.yaml
  - backup.yaml
  - httproute.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
    releaseName: miniflux
    namespace: miniflux
    valuesFile: values.yaml
