apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Misc
    gethomepage.dev/weight: "30"
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/description: Home automation
    gethomepage.dev/icon: mdi-home-assistant
    gethomepage.dev/href: "https://homeassistant.net.ecksd.ee"
    gethomepage.dev/pod-selector: app.kubernetes.io/name=home-assistant
    gethomepage.dev/widget.type: homeassistant
    gethomepage.dev/widget.url: "http://home-assistant.home-assistant.svc.cluster.local:8123"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HOMEASSISTANT_TOKEN}}"
    gethomepage.dev/widget.fields: '["people_home", "lights_on", "switches_on"]'
spec:
  parentRefs:
    - name: shared
      namespace: gateway
      sectionName: https
  hostnames:
    - homeassistant.net.ecksd.ee
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home-assistant
          port: 8123
