{
 "title": "Envoy global - by Fangdd.com",
 "description": "envoy global看板",
 "tags": [
  "envoy",
  "test"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Max Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(envoy_server_version)" }
   ]
  },
  {
   "title": "Global CPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[1m]))",
     "legendFormat": "Global CPS"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m])) / sum(rate(envoy_http_downstream_rq_xx[1m]))))",
     "legendFormat": "SR"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active)",
     "legendFormat": "Global Connections"
    },
    {
     "expr": "sum(envoy_server_parent_connections)",
     "legendFormat": "Global Parent Connections"
    }
   ]
  },
  {
   "title": "Min Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "min(envoy_server_version)" }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))",
     "legendFormat": "Globlal RPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total[1m]))",
     "legendFormat": "Global Routed RPS"
    }
   ]
  },
  {
   "title": "Upstream Retries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m]))",
     "legendFormat": "Retry Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m]))",
     "legendFormat": "Retry Overflow"
    }
   ]
  },
  {
   "title": "Envoy xds status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_update_success[1m]))",
     "legendFormat": "Update Success"
    },
    {
     "expr": "sum(rate(envoy_cluster_update_failure[1m]))",
     "legendFormat": "Update Failure"
    }
   ]
  },
  {
   "title": "Upstream failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow[1m]))",
     "legendFormat": "Pending Overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout[1m]))",
     "legendFormat": "Connect Timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout[1m]))",
     "legendFormat": "Request Timeout"
    }
   ]
  },
  {
   "title": "Ingress CPS / RPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_rq_total{envoy_http_conn_manager_prefix=\"async-client\"}[1m]))",
     "legendFormat": "Async Client RPS"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "ingress Http CPS"
    },
    {
     "expr": "sum(rate(envoy_http_rq_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "ingress Http RPS"
    }
   ]
  }
 ]
}