# Alertmanager → Home Assistant webhook URL (namespace monitoring).
# HA automation must use the same webhook_id (path after /api/webhook/).
# See apps/monitoring/README.md (Alerting).
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ha
    namespace: monitoring
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:rTmd+8rj3jNxJdKiEWif8ZFu5E/vuRpG6J8Cfb117KVbiGno0twAkWbQKCDnri4+eP1rSEg+GZzyj6HetT1jQgfaAD5KP4SmwOsJcnlqBp7FhCgJavT7XvVs59k6J2F0wVzD0EkhctM2Vk9VQPBYbzHpGiUqZp5q0VgK,iv:HViXo7awLE/sok88acKYKsyv9DzuC/f+ZqFMBmgFo7g=,tag:/4g39lkrvl60FLZ5IYOUKg==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Qk41eU9OVm01NDJOVlV6
            MGNMQ05tNGk0UWlvWHpWWWVBTU4xU1JFVEYwCitqREU4bkVIcVIrOFh1dVNOYks3
            Z2F2MjVCakpOL2F6MVprcG9XUFM2QVUKLS0tIHZwMkJ0cGN0aUQ0YlArQm5VWWNX
            ODZGTEluNXhPVzBSWXpVYjVNeGhpVXcKxTZHLPDBR63Fw8KyZuwCIHc8rMd+ohy2
            9jw1q0NpgopgSfLL/4PGAiQEZvCkztF6XgQ6WXlJ0WMXPwRz4oY1Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T03:43:11Z"
    mac: ENC[AES256_GCM,data:wztXOevwh2kJG78LoXgips894ucqLx2jyN8jkJE1fkklxe3aeNMmx0VXus21XHj4RKkJHe9IoRaTvopwDLGF4G498fUzh3hWYAtcI774i/2+2lfjtxd0dOnc6Bkin+eX7w8QK9rPt7TyDH8Izh7ko1SoLJ1uZB7hhQUa3oia47w=,iv:37zum31SxOBmbbeEifotpRmnEH7fli5kU+zIAez/82U=,tag:KA6NLGe84bH/nXFdSRiS4Q==,type:str]
    version: 3.13.1
