# https://docs.goauthentik.io/sys-mgmt/ops/geoip/
apiVersion: v1
kind: Secret
metadata:
    name: authentik-geoip
    namespace: authentik
stringData:
    account_id: ENC[AES256_GCM,data:KrkDXHKw,iv:qoocGrfV7lOdsRK22hzfaFI7FjGVyW7D7LG0k6KyPRA=,tag:YJDbTl+VRHI62MsDMZKgbw==,type:str] #ENC[AES256_GCM,data:npW/aOYdfYrFBHukoA==,iv:0FAatS3ejKKRT0gMLxNAOPW7IpZ+1ou5CULIFjKZFbU=,tag:qkxL6B423q/bxyXX+Aq7dw==,type:comment]
    license_key: ENC[AES256_GCM,data:i0fg4XMk5ljEVIOb0eMmd4sOUZXN9mti/cHO/zNlznXp9cmYL9oZ0Q==,iv:GrFEh6Bn5URUqSsy2alb0WZJL2Vvv1z9xB35McHS7O0=,tag:SwF4HTIqr0kfb2DPW3uaoQ==,type:str] #ENC[AES256_GCM,data:E1r1t+xp1p39A8ZRnA==,iv:iYhapyIcOcQaYpruDDteSOkrEXLX19VBRXHCERmy9q8=,tag:3P2kkwQKJK5TxMEYB9U7+g==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R2xJajVOYW9Lb3FOQ3Jv
            TXE3U0VCdmpqMFJnZnVEL1NJSmMvMDJ0Z1R3Cnp6N3ZIYVZwbU1PdzZSbGxaM29V
            Uk5rMitsNjN0amRHODF4bVZyRkM0WlEKLS0tIDZCR3BEakhmTDdRYncrWlFGY1pY
            S0NVWDVJZDhKaDFmWlRwYkp4YXNMMEUK8FauaeQRaacvbvzXwJ/2s17dgzfy9RRr
            C0n3t28mtNUL70NmTltHZRpzzxY8eavlibFPh9K2loqLGqynJlNTsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T19:35:22Z"
    mac: ENC[AES256_GCM,data:/d5GRte1ZMIg8QG36VWxuNpmocyuZ1mBoM4Ypodal1ChTxEMrH2DkdcoOX1xqmLb4QdZHYZ2YuxaCdHNS8Xrt9Tj4koIMP4jd4P9Ze7FjmXAhVUbsG/2lolfUyKr5cwrr1h2bSILyiLDkvnJlFdpTm2SqMsX6AdPDkOmJ3lYyLw=,iv:GaVan8G96gJv+kEgI5XqMqxtN+ED2g5tWia3NwP4lnE=,tag:0WAe/L2Pu60wWqmFyG2wFw==,type:str]
    version: 3.13.0
