apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:8CoDzruBz8BOs3wrBtZIyygQ2ANGnsL30ZKI52D1dL8IL5r6Ld6eqqIEsovAkTD5CSQ6dklfX4JlaRh5rwuAfQ==,iv:3XoufFIQ5Msg6cR4qiwcMDFjV/c4jd5/J3tx6R4q54M=,tag:o1IswMjyac6WVkB+u3uaHA==,type:str] #ENC[AES256_GCM,data:RRvkoODKhBEWZ+RY/w==,iv:p5ZsrrvLa4NEOJJ5DarP+CYdUQe/PHacrZz4joK4AZc=,tag:KjTJcBo8b7N9XFznJSaw1Q==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcUZ6VU45NlJ3Y1ROS3k1
            YUh3VXdPUkYrOVgrTEJIRUMzNStyUVo0YVhVCjZkZTZmbFgxMjVtZVR6cTN5cXR5
            d3o1RGE0K1luOEFVVDhTaHovdnNTU28KLS0tIFd4ak9GcmFQYUJmTUhia0N5RXZi
            cm1MZGhBaGVkOEZacENzS2xBUUJTUmMKbiv8dbMh4kU/SnWuaxhk9s/Q7EsBUgmK
            ScgI35C46Ugj0oq+MotSg+swj00v64fZIWvTCH8kkojsouVgpw0Zyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T19:35:28Z"
    mac: ENC[AES256_GCM,data:WR5XKJhuO55dln+1cPqoGR+2tJyry03de3PObPQAGIvODuqatG9Iks+3S8t6fFMIqP2n6wxvFqukw1WqEWyMe75Ag1V7e47I0vHmsuSv/3yoDOtnzztXhkVWob8wDZKQlWu+YpZHSzFPSRelDVNE+lz5Xb9U7CsY3OClAZHUG+k=,iv:J8hjODOrjAtfE1sjEF1XR3/pP9DRouC3FgnBqcJ/mfA=,tag:X/6gGq8WdSAs1H9vGuY9Og==,type:str]
    version: 3.13.0
