apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: authentik
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:UIMhc010V88I5SrBgEKUXf5DRZBa3zeFSi0=,iv:T0mx/D9qADFyo1S4ZlYUCMOKbZb0MBeZleFey1xjl24=,tag:+vompb7BhgZczCNc6mdprA==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:cciqnoWn37KvFlezziq95J4PvnLBo24KttVWnjvJe7JORz6CwARzfhxMxrJAKRV/OGTZIlvqbDmhoZg3uYUs3Q==,iv:NLSuqAIcnu/VvzQRsmXtl6JmweRpkC9+gYklfFIAWg8=,tag:v6uLyXGIFVNopooPYIgtgg==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMHk4dk1GWFBTWGQveDRR
            RnRUVjlNdk9sTzJtTTMxQ3Z2cjRwc0F3WUVJCk50MHp2UTd5WkdPU2xWNmxLdWxu
            S3oySjA1eXVwYnU5TGNFZ282dmJuaG8KLS0tIDJ6dCs2SFdwOEtLTk1tb0JmS1dL
            V0tBckJEMnZoMENUZ2pUMjZLUTJEc1EKg8itBFTfZA3n+w35SWBM0YLsVZzBWy3R
            MKecLfBEnLdy/McuS0TNqtaPqL8a7C+s6VE2A+l9VVnmdk+hPGJ5TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:uYcc1vjB/vu2a4ExD2E3RLnIbOmvvY3bHIez+m5W0U8e3gVdfgTewUYI5rPW5bpsnQC29cAoNooWR6XzzF0bQU0QlkDe3p4KqgY4rsNsMuokKwzqhl5zdeLcsbK8+ex+7RJa8874M+jWI/BlYPGOErTEpys2q6/Xe382RNv6IbI=,iv:hHSHgWQTE18C4J7c3DSJqR8vl8MtfTsbu/YSWsOsnl0=,tag:MkZ6So6DXKrbpA5jJs7QLg==,type:str]
    version: 3.13.1
