apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: authentik
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:cM7rVLpWRAYgGcXaPOXr0NV2aBP4alFuVe0=,iv:h63A6aIbx7FsQUcUjWAdKVkKZzIFxyPuW7GifRXHMbk=,tag:Y9vmJqSmIMj3SWDNUQ8j2A==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Q7y5EiY0gIL18dYHMnY0Lofw3zDnDReB62Ivo0oI74VKNLZF3CABGHsnDeSxuvP27Xlu+iwjal+5K7Kf/pl7Zw==,iv:qsVjv++KCtU916fgJe5bjlGhb5f1cSc0TazlGkbSKc8=,tag:CYQqrrVhjaolGvhWwir1HQ==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMHk4dk1GWFBTWGQveDRR
            RnRUVjlNdk9sTzJtTTMxQ3Z2cjRwc0F3WUVJCk50MHp2UTd5WkdPU2xWNmxLdWxu
            S3oySjA1eXVwYnU5TGNFZ282dmJuaG8KLS0tIDJ6dCs2SFdwOEtLTk1tb0JmS1dL
            V0tBckJEMnZoMENUZ2pUMjZLUTJEc1EKg8itBFTfZA3n+w35SWBM0YLsVZzBWy3R
            MKecLfBEnLdy/McuS0TNqtaPqL8a7C+s6VE2A+l9VVnmdk+hPGJ5TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:42:34Z"
    mac: ENC[AES256_GCM,data:q+qEBTE9hoogIM3OW37nSd/tN7rC/SjKMPVtaeF74qlLM3dERni6OZjHqCtMp+vNaiAK/wHkoNjEF54XNoIPPraIeX7wRUuhPVNQJR/EnTp2kPz1qEhXrqo5i/ZmbGBUzpqyQK/9O22NOHUv5kgQYeeFi8xiODgKFL71xZpf4IU=,iv:KiqLOkKhpMEtz06aVK65Vm5gvlwadoCqukotTCWeWnM=,tag:SkDlSTTfxntVV3yuxooLEQ==,type:str]
    version: 3.13.1
