apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: authentik
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:2y8FCYv9h4eHPHEeT29KBPVvavj8uEIh0b0=,iv:nWyv1q89IT1VNtHBl38F/xQdsAh/+fqLP+wOGo0vKU0=,tag:HSbgLyyzfl2x4Sf4jx208w==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:jwwglT8WvgSlz1fpv78MyG+0EZMYLblRrTdMO0LGWB8yaxRxDHziy9RQP1MXLjcGcD084ggj7pGXuvrWN97yew==,iv:U/aj5r7JY02vxXG2gHyP61RxmUU11HmCpt4nd+DP1GI=,tag:JKNB6WwhN81j1PrdjpZpiQ==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd2wvNTJ2bmtEYmovSnhB
            UnJyQllEaWVFTzlxVHlVLzJJTGJQWmNNcHpJClgwUUlVdXNhbEMzNTFFcXZ0c2lO
            eVlPaXhvUFU2dE1aRzhzTVVtUEVFUDgKLS0tIFdVMWZYQXUvajMzN1phUnAzd1Jk
            OTJqaW1nU3hVbjczNG4vNnRwMnQ4ZFkK9Ddk8MJTsk3mshROaozWF20h3z5Uv1F+
            8zA5P2+5KxUSkjHG+VCyZqBHfrVmZbOTPMoNzSfd/pNqVlDP63emGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:Ezn7eqG8BM59/Gax5VvKDXFFJ6fFySF5glA9qGiCo4Ojqd5llVZM2YW7htMYWKiekwCqwU04ykB4TPVriBd5tB143qKUTTO8xQcRybUMZFhZV/Db5icesAJmwCmuuL7Bpvf5G0OYUixCx+05hjqSKMsiEIofjqi1PHNHcPHB7Xg=,iv:jGN9Jy7wQhpo0YYg8SpgewjCG70vUUs3SgxFVCrh5YM=,tag:+JS6Mao19cTXGEI1wzEexg==,type:str]
    version: 3.13.1
