apiVersion: v1
kind: Secret
metadata:
    name: authentik-db
    namespace: authentik
stringData:
    username: ENC[AES256_GCM,data:9hnxjt+TgNBh,iv:BCRrk3G3GkBJ9DoDNkFBwKCtp6BMRjcp3Eq3bm3VCUk=,tag:7vRU/Co01QzlIs6B8nZ1yg==,type:str]
    password: ENC[AES256_GCM,data:MNvubub3kSyh6FECMEcVbR2acGCHOkFbmt+bVALs8I2KjZhivDEuSGk5awk=,iv:QguAbiUOBhLCnrbChTgN0nevlbG+Wz+qEFY3n/n99y0=,tag:hEQVSeJUQ1LkETu+Mkh3xw==,type:str] #ENC[AES256_GCM,data:V1oDhjnDsaU+webltQ==,iv:8Mec/AGmOUFZGGzQqjI3m2bgJz07fX4WmlukZJ9CjvU=,tag:uQ1ori9/7fNioVg8yYB2Fg==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVWRMZ1lGcDdrZ1MxazJU
            NzFtUDhHZktMaWlldDk1VmR4cVE1SzFmYVhNCnpZS1pSdmJqUzlsVmNPNlpTZHRw
            RTlzdEN4TkVKdVhXMU1XZW9GSWlyTmsKLS0tIDViWG1vdm1OT3lCYkIzdVpxNSt6
            czRhaFZjR2tOSVJocm1iR20vclZ5cDQKWk9th/52lZt4/PPn2RYrBBEoShprRftf
            LmrkcFhWlF+OKTrPELxVA4wQZzOGKwhIWTa4DNcdYOFn9fIRg95kAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T19:35:13Z"
    mac: ENC[AES256_GCM,data:2I8GjFgViHidm1WZwyMGqqMJwyfK4s/zUOCpGDKSfnISr2RKfZBIxLoCPYTe6RukkohE2rtGSPRTZD3VtTc39JUnJrXcy3/BssGj7x/m9AQYD9bmXq0Ayl2rE4iEHCQuqf7EZv5igJJoYJDOOaO2N18awGgAdGMJwVCAuGKZcRs=,iv:DTAiUuHz4cSbb8uGb8Qh5f6cAdoHJFlISn8d824DfR8=,tag:oDa1MkcWtL81gIU8FkFSCw==,type:str]
    version: 3.13.0
