# CNPG bootstrap for apps/bitmagnet/postgres.yaml (owner and database: bitmagnet).
apiVersion: v1
kind: Secret
metadata:
    name: bitmagnet-db
    namespace: bitmagnet
stringData:
    username: ENC[AES256_GCM,data:CrzWIjn6HjDI,iv:YuuCky87/ewmwyU7xIUDjWqN2Z/7DTot8wrC9SX+1nc=,tag:TjJBiC0vrj5rwP3NQxPlFw==,type:str] # sops:encrypt
    password: ENC[AES256_GCM,data:1ZbLnoLlVeKc/tGCPg0y6/11ljq5v+qNfKWaHOTqzFI=,iv:TGrxanRRnji+jTzxA2YRTe9C2m+iBV16El5KaJsaydw=,tag:kSY6JgPMAcNz7KM33yyMlQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdk9mWFFEV0FNaG81WDBy
            WnNURVdJdHN4Q3I0cmVldFY0K1RWdFJNZVdBClFvcDBNaTc3Y0krQ1F1eFRqcnd4
            TnpVQVZUd3l1am1sU0x3OHhDOGQyVFEKLS0tIDZsM0F1US9MUCsrQUdHbkxobGlU
            S1MvNGNRS0Vab3J6N2Q2OTRCVlVKSEkKY/IEifGyosOtGtyBWwZ5jBqp5PqeXmBM
            gIXuaNGzdrYhRGx7r5Cu+sWlv3Xcg9e2j5ez7SLtwdWUKZjFmY6EyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-20T01:24:59Z"
    mac: ENC[AES256_GCM,data:xZclJoiFe22DGcWQgeMO9wniB81ZJ9UJgSwoXNpJ9NHfrExO59n+36j4b/YrLeNMiAAasfIYgKgnNfkdWKHBCF4Uc9c0xjuaOPhTA9Gie44WeoQ736CNAV3U9sGT/A0kQO+TlCvq6xPUn4Hc1ddMLG6uplIoIXifxFEGLWHZ/vs=,iv:5kwf+6870c/NZLr7+uQP6EtO2ZEtvMN97VXQ4EKPAXQ=,tag:+8I6axc9FeaQ6PTQK2+wZQ==,type:str]
    version: 3.13.0
