apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: bitmagnet
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:uZT55H2sLajM5CYCOEG2O50r6nviPkt327Q=,iv:5qw1nm8CrbTpjii3g220aR0Os/0UwSft0T+FvX9E6X0=,tag:vkw3bctnHRJiJF8uzcMEpg==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:bgS/uI9NGRcb3jc9tBR+wzo25y3Zk2RxUKrTPe1eYbbjf4wnJDBHhRO13DBjdjli9wZcnah7fo6lYQhN3IBQ2g==,iv:Uqs6fsxYapAcoM1mJJVr/o8tgoF6mjHqIEUVv6b/DDk=,tag:hSLa1+gURo30ogvSqD6MqA==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cUZRbDcwaStML0pMajcv
            S21FZXhXRVhRN29GWHNyRVBQYUhqUHdsQ1dBCmRXYm1nRHRwNW8wTHE5eWdWOGNk
            dWZsZkYvSUREWmhINlpsNDN6MU9qTGsKLS0tIFVWcjYvdEF0VTlLUFlkb1hrQTNL
            WkphVit6OHBkZEhGSkJyd3B0ZVFzQTgKam9X7o4FbRbS87wQda1YOGy4Tq9rGu2z
            GDJTPIc1oEmupBigoxvSOzugO4IR5eh5QRjK+R9joF5sG5+H+khyMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:MhE4R163o7nm7g5HKWV3BehXTX1vpY/07RoBmlda8JEzN1aELRYSNbzRuUUj63naBAPd6p8hMg7LnS1QxnIiGQmvxyBaEj4/GiEMjoEWyjirdRTaslc+J2wDg0FYdDV/feQpJUEIh20UeGcOsACxTCjKmqzKt6Y4L0qCoNje01M=,iv:0smRqeagNJdQiRCsKdJGGOFdza3RuukzECRxKft0SY8=,tag:bumPtnplb4SWAUQnT4nDmw==,type:str]
    version: 3.13.1
