# App secrets for Bitmagnet (namespace bitmagnet).
# TMDB API key: https://www.themoviedb.org/settings/api
apiVersion: v1
kind: Secret
metadata:
    name: bitmagnet
    namespace: bitmagnet
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:qEpM29Kp574KSeONRMJ9mo0YTksI2hLyeiLBjZk1Jj0=,iv:XjhqyI7H6LLBWZ+TsZeRq4zV42hGHaDorBxvSBFwR7Q=,tag:OOPoXBXy+TXHl2t57LnlzQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSzVnNmYwOUZEZ252S2FI
            eFZYeWRXZitDM25kcXZ0Sk9rdGhsVFc1NlFRCjZXMU14V1pzeEl1cXVIL3RyekUw
            Snd1YlpMVHowbk5xVFZBSW1mZ29PYXcKLS0tIE5YTWVrSWZZMWtDK1JGQmZmU3F4
            QzJ4VERSWkovbnRqR0hla1hhUzVSaW8Kyv+6Ew9t5/O718X1mC5140BfwqIhcpyp
            7AaSdZLRBoSCjMcU4NAo7AlevArEFs/KnXue3ahJsr6M4F74G7h3hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-20T01:25:02Z"
    mac: ENC[AES256_GCM,data:ixsp5+2AWIwSlsK6BSxndYapGiM98bHVdJ6OXXmNP6iBO3lmdf1cQALubeTzmXSZmGYA09vg1TLXBTt4RvarYI350ytkUjlckhp3s7METizcASN/yNYkNmy2Jo2cDaqcEzjGLKBHVVpUPv29EXuJTjopjo3zHHmyQ/8L7NH4V1k=,iv:mvjUHRKFu0ztjL0yc04DjI3UNSVD/wMMoAVDNu2Q6no=,tag:vFS4tO/lonJ3sBOO7JSaPQ==,type:str]
    version: 3.13.0
