apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: bitmagnet
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:E0BI6dGjzA/QBMEdmdwJPkc3sOTSvE60GaA=,iv:0C+LBcLu4uL9bhlZu/8ydYHVzTXIW/HExFaTti/JZpM=,tag:lsKxwVRKkDgMGoAEiU//MQ==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:HqSJvJkxv28tq9Yzmh2a+RnPrGPlYDB2/s5NXsoeLVENrShVBRdL3sL+oQCNmAwxXmhB9vqXim2xJC0J5+7YSw==,iv:gtVZLF+rgebs/sXsPMOFQGP6aXAyTMWaQgDx1Jm2Hd0=,tag:NRxHLYf005meV+DhQ276rg==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTkpPTGVMa0xJYzBjd29m
            N0R0L29Ya3hnZWQxOVQ0eDJzQlAyRTdEU0NFCkZpYlRZUTBaQ29GL2NUMmxOTzgw
            RVRZaUp0M3NHNzlIWW1ZMFYzNDE1M2cKLS0tIFJzdEdDWjRpK0JkdUN6cWYxNGFx
            Q25XQXMwZHlZOFpxdk9mb3d1cldUblEKhgOpkfmWRbOaXAc8elEgq5+Y02l0waKi
            dnz/xt187gf0K3GHFgFoUyJc6oUp+M9g6xoXODlIpRmgOkCj+aMxYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:W1CrMm5SgnGy/sUKjsv92Msa8FlK5CbO6uuanURduzGxW+QTQl0zOMph3YYe3SaaD1njGeZluZraIEsujeEDBdW113UpliSRduFQKM9WQ9925T0p7mt8WBx4F9UW5qEgYnKW9FtKDM6aRx41+oKKUGglh4JSr0IPXNP632tw6sM=,iv:Z2tkTBaea+MFJQosPwzh9IlDsgmuZCNv6O6q3YguIoE=,tag:E/SUg4+SGFNMxLgLDIFHYA==,type:str]
    version: 3.13.1
