# Grafana admin login for kube-prometheus-stack (namespace monitoring).
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: admin
    admin-password: ENC[AES256_GCM,data:VcZL66uv15WAabDeM3YdRt3B426aSMO9iUxXfTVeUdI=,iv:WhUg8OeRIzjdXtSG9vG0iiBJB/z878qXwp4Scd0wIbw=,tag:IFOm40QOWOtyP78xZK0cQQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6KzV1VkxtT0Y4Nnd2Ni9B
            RFpkak1GdWV3d3hYVE44M29wdDFaQkpGN0Q4CnlVNVNXMndNVytOMDBDTnNFTzE0
            VlZWUzREM3ZmZEtLNTZGVmU1czMwOTgKLS0tIFJZMWhkcjRXVWNLMGJCYTFPMkhR
            MlYrS0ptYlhGVllEaWlqS090ZlpoTGMKVa8FIg0/YVpoHENvxpx0Xl3yGp3VftO1
            +ihb450Gzsx1Lcad4U5qHp7VJpGkYZCUzGsyvbWDo92BQdICNb+X0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-23T16:32:28Z"
    mac: ENC[AES256_GCM,data:KgKSqeUnxNBzd95+Hg9mn9RnxMl2e5UBPHdXwEcC8L+mKEKY6lCblOGDb8FSU5KxfqHBsuR+foR/UoFxLRsOZ7oyRIMIVPDxMInAl2z1pgqKpI2HSI18t8ZNX4OHM1MWK1pcym0byePsHrDnkmS5Ea/rRzZaM65v8lzcZ4aBONQ=,iv:kcnROHAuyqPCI29bG+O6QM3xA6SaRqf15Gfr9kB6D0o=,tag:hnibDVIaKN9zc9KOW3V/Ug==,type:str]
    version: 3.13.0
