# CNPG bootstrap for apps/monitoring/postgres.yaml (owner and database: grafana).
apiVersion: v1
kind: Secret
metadata:
    name: grafana-db
    namespace: monitoring
stringData:
    username: grafana
    password: ENC[AES256_GCM,data:HWCIyfcGBiYBCpysNL5CwPeeDn5k4tc+wpsIdw98cX0=,iv:/394RM0viKi92YqpkSGXN0ONheAFeV/ueMx0bfpZ/8Q=,tag:/eusZeIJ6EHta5jMuWlWfQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TXlNVUQ3QU5KbmMzNi9O
            ME9zOWFFWks1a013aE5qWFk1REJabUNHRWhZCmdGNisxTlpPTzJNaGE3OHlRalFH
            ZHRmVmd6c1JiRXROaEVBZU9tOWN2aW8KLS0tIDhIbTN4Z2NPb0JPWGd3RDVMdkhD
            b04rTXJvRDlFRHRwVnYydmc5Qkw1SzgK1PXdvqe/QzOOBYppMd/dVkqIfRvZEAi9
            KKYTW5xWGpb34rqUAZDJoCIuDn8K7vI+kmTd676PFIUj0xwkdFsj8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-25T07:48:48Z"
    mac: ENC[AES256_GCM,data:KgvMhF/bVP8k5fiKieDI3GlTAxCC4HI32KvDwlIM62ADchzaXIA6k04NC8opxOc5zx6kwXI12YohGBNXENcInJM4wYU61D9lDlhpUnzkkGdZioZ1/udj8CB6qtCznirBeZZFvF7ySmLMDPQXsStF6I6asmNxs8wWPOj0NFhZHtk=,iv:G63XNnkySlRuPbgY8t41zW1wmCOkjdSF+ofvl15LfRg=,tag:tO4Co8IYQWynt4G7lZwk7w==,type:str]
    version: 3.13.0
