# Grafana Generic OAuth — Authentik OIDC client credentials.
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
stringData:
    client_id: ENC[AES256_GCM,data:/b4GrMPiCS85z5cnrRMSrs2i0AgTjX0J3kkFa+DcHDDvQCe+6coT6Q==,iv:n5lECIe65w6VFuJR8vxv8stVYeSWU5ArDgmlwiLjIf8=,tag:o5L9VdBE/ZC8pHhknxezYw==,type:str] # sops:encrypt
    client_secret: ENC[AES256_GCM,data:uqsDAbaTYweFMK3A0g0P7sqjRflasyayiJD2dvYlgVlGQZ2YN5ORl9tlDjMd5B+65daw6PlBH9i6D/7g4OiKSBtZ5rvyTyC7ZKEGuAi2bMWEJKV+U2MJBvm46Ntk2fi+0eKJVNAlDv6r0bThe6ZIk4QsBqNrPOMjaMaeiRzdqVU=,iv:4/6fWIPOKNwiJxKN2LoppQ2AkFqxZaaWB8IisPCs/B4=,tag:cnz/tl2JO6QONuaUzttctg==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVGlkSGV1cThrWVJyWWRC
            bXNvd1FFZjdXN0hCTWZNVnVWbm4rK1FscFJRClV1azlnV0dBK0E3TFhFdlE2N2gy
            U1ZqNkpGekNHaVRjN0xqQjVtUTZKSm8KLS0tIGM4amkrSklGWEg5R2pqeThubDU5
            S1BmaElkL2RCNXp4Tml5Vi9saGkzZTAKZOQ4rxulm9P+uw4HQLGXzFeyBMox2gF1
            YxaTcM4ncNOQbgvlkzcDSc+S94yevrwAQ3tqCA1r9UeqgBBvOkypng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-06-03T03:54:37Z"
    mac: ENC[AES256_GCM,data:YYb81Ta3wucKAEhMHkUNhK8wTZ4U8ZOL9mULUqsrJ8AuL3mtZ2iB7MAPCE0C/4cJamxhjp6+IN1omi/VuVloCpBQ1CPvaGwTIk/+cWfx7YrUFEj/xgIDXV/9pehFx0G1Kg41WPmkfax4SkLNdaow7Rn6hjAs3/ZIaTQJ51vduU4=,iv:lCRV+RkfNLAhTSe28aTfx0iGv0PPvGjr4mC8lK8Y91k=,tag:3EyPgokECktqP0m0NeAOig==,type:str]
    version: 3.13.0
