# Plex token (https://www.plexopedia.com/plex-media-server/general/plex-token/).
# Used on the Tracearr Homepage tile (plex widget).
# https://gethomepage.dev/widgets/services/plex/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-plex-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:Yo2LugWENV8uN6lD490ta5qAkAY=,iv:Q5RFhjHbmV16S6qzIHzBbTOOsDwdimUtZZTLQ7XeNQk=,tag:NwLGxvyB9iAZR7Cvhw5hmQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVkQ2Y3F4ekNsbW5jZmt2
            WVAxUnVxbS9ZbmUrNklBZTkxTUNUcjZMNG44CkhTK1hrblZVSkFWTXIrRDdFaFNM
            OTZrcGk5Q3RjcXlGTW9XWmFrOVBsS2MKLS0tICtWS0JJUXlRK2ExUU5PMWJSMEll
            NC9kb0xKUE9xNitrOEVKUnd1WUg3eXMKdm1m8SHA/7VYxCZbP60cEgazs9uqgjuU
            PlJsvZ9iXE6zN0JOEBvOkcNxCIFaq55iJVogw04RN0oCXgg2pdeLbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-19T05:48:49Z"
    mac: ENC[AES256_GCM,data:mPIkoSe4fH4D3iXIBhk2IqQ8/amDflgNLSfLDaSXBoqCEOaBS5cyK0V3Cs7TSwWRmVcniB9sFpa1XqXCOS3UjKFUzyVoq76Sx0FF2IJlksHXJ7nNVoIRGR3t2XUMyNqd572ABTBhsuFJLwKWhoW8JZqNLBaJjBfucAHFSnJH8P4=,iv:JaaHwExOAmYd+a+na1qYKDaf2jWHgci9b21zS5u7CJY=,tag:vcR/0e20itYgPaXs0BFQ/g==,type:str]
    version: 3.13.0
