# Synology DSM widget (Disk Station) — read-only monitoring user.
# https://gethomepage.dev/widgets/services/diskstation/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-dsm-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_DSM_USERNAME: ENC[AES256_GCM,data:yZ9M8+hrMtmeYA==,iv:QIJpOf22IqJ08ytgiYHbE8TcsOlCZaisoA/+sIs1TVk=,tag:cXXJZjzJeyfCL/7xqoHE+w==,type:str] # sops:encrypt
    HOMEPAGE_VAR_DSM_PASSWORD: ENC[AES256_GCM,data:Lx0etf3A9r0GrE/JsGdCRaQuloT4Bdq4PbjLDSvf,iv:flgUqvPeD/ky+w9PiIypiS+kquuW+G5QXGPSNMKQmCg=,tag:049xUqS7S6xDYjGflpo2sg==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcWxJRUVSVnVPbFpaQjBo
            Y21zY0dyeXpScEwwZnNvWE5iKzMzRlJRNEdJCnAzVjlZaWtKUlNROVRnWE10YVFx
            WE5rTG5ZWk1IRG5Ga05GaU9oaVRodTQKLS0tIEtPSXJRaTZ0WjFLYllyQjFjNW12
            QSs4OHhMUW1JYm1YbWN2MlhsVWhtdFEKrWXdyfFhxgSsEwbqKXSQgjji3t0JKwPO
            UBl/89E+SUGxAAxmVEdW0xNK/Odq8mW+ACoHoraRAiH436i/I7O35A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-22T15:39:56Z"
    mac: ENC[AES256_GCM,data:fjgXAIpsJN0aDfhb5L3KFIaaNgENJWkp9jzBTAzZIwecgvW3zefJV5SHDSp4zPrUpQm8a2fwFtIleQ9/HHMM9ObJJguAVk4XDh4dJ83m/Gtn149nrdBWJRv7r4fNOumH/qrwnPa25LbDL9YYzpuLObIh9pOwhR9S/Wph0ZG655I=,iv:lGv7Ye1N4WurMQ/BlJQcfSeA8CsCxOyWSLEngO+1SdU=,tag:7oguzfgWDWdD04eSnyw3Gg==,type:str]
    version: 3.13.0
