# Radarr API key (Settings → General). Homepage widget on the Radarr tile.
# https://gethomepage.dev/widgets/services/radarr/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-radarr-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:u4Eee1xDmXTyQ5O5pHklHxb6tdwdS53BHB36zBR50lc=,iv:gpek2RSLgY1EQCI+DCH07wd8hUKzBJ5R2eUenQ3BIDc=,tag:HR2wibGq3f7wHHvRc5/sMA==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWnYvQkx1VGxsSFZPSW8x
            aE9nRWFCQUhidkJmdXNBQlJ3dlBXTFd2SWxzClA2THYyU1k5TW8zUVVMSDFyaDRy
            ODJmMjcrbndlUWFzSTZ3d0k1ZEFrS00KLS0tIGxPYjdqeDFnWWQ4N3g2a0libWQ5
            UFJSSTNod1pmV0lGdFM0d1NCK0pXRmMKDhuWjQi1Dr86I/2pFiayf9NAGBMgoQD6
            w0ptT6wGJx0CTw3Y/ZjbGn+Fhr2Rce8kIiVKRRgn6xMLBaj3oSEl9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-19T10:22:53Z"
    mac: ENC[AES256_GCM,data:0n82Hvq7sGM0ePZ3v+dbxARut292Ilf5FzZN/CuVFI9NxKS565bVPlgF6+sajE/iFnqcj6lqnQ78nXP1g04I+jNm0lxZv+WKy1Ev8zTSv4ikiaIR9q8baXd6f5qWARwpVcwSRBZeZ1utnKw2eOzRcxpFXf4iol8Km4BWvzxHZ3w=,iv:uzyTldE31DZt1IyaZN1FKHrE2ADq6kNPi89DVRcOo1k=,tag:43bLN8OamDYFXH1sZqE0hQ==,type:str]
    version: 3.13.0
