# Sonarr API key (Settings → General). Homepage widget on the Sonarr tile.
# https://gethomepage.dev/widgets/services/sonarr/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-sonarr-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:WhjVaXs1QGobyMMPh2cHUSZPPPRtrgcctHGQYKpl9Io=,iv:Q5lYmr05RzLvbGNXnKvBk6X5D8a44REivjaDMbybz0U=,tag:DY/00nFf6QD76xq3QA4j6A==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzazdiL1FSMm8zTG96S2Zs
            R1ZhcUVPV29wWWE3QnpoVXcrS2JOd0Jza2dFClU3cXFieE1UYzB0SGs5M1N1Yy91
            MnREcTZvZTR5aXN6YkcyTDMrTnpZcU0KLS0tIG0zdVd5NFcvR1FvUDY2aTZIVmFz
            cjdIdG96T0RubCs1RDIwSnhraHpHTEkKIia2YFfyACvJVPH47lXFV1ffYe74z2Fk
            9nxUDSHfyAO0M/LvB5rIDrrwW47b7bVojbfHm0gEinv9ZC08PpWKyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-19T09:52:46Z"
    mac: ENC[AES256_GCM,data:cFXyijmBIvQliMw1cmnmKfoEtGJPVzgFt6JQEl5pW3k6d61fYx+qgfwn0wsAbDEXeNXAbRndQ5X32k5YhQjsoDS4h03OUgzZ5l6xesMP1CnVahZ+CqSuzzXTRjWO7g6j5j5CzGuMq0vBL33B4652/BYzFuzStW+ZDKWEraUrnIM=,iv:i7RX4fwiS1CT43YLWMrSIjBDA3RurozR4E08gwsQXBc=,tag:85mfB7TkboPYw8jwW6GJsQ==,type:str]
    version: 3.13.0
