# Paperless-ngx API token for Homepage widget (Settings → My Profile in Paperless).
# https://gethomepage.dev/widgets/services/paperlessngx/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-paperless-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:yyLUIk2qh6RNvn2C/hg88vERCEEte8FBUUoFi05qqZwmZQdOIwxb3Q==,iv:uNT+d6zYS0THifSX2ryL+kA09qBH8YEynjEBCeKDFg0=,tag:F46SYkdSf8CrFY1cbY0W5Q==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS0RxS28xNkxGL1lOMWZY
            dk82U0twT2NkaW0zaERJMXlBOG1lZVBMVnlRCjJyNm5rUjFxQ08zVDdxMUJqSU5k
            eWVYUDFQdGRPd0RhT3hVeHFmR2x1bUEKLS0tIG44SXRLV0RmYTQ0NVcwQWNKRG5G
            eVVKdVdzbnhLRENKS3dLdWdtaEpnM0UKogT/GYEJM/DgDdLD58h59LHq3p4t92v9
            ZOshqqEu0cw696y7aUnXcvMI5ZnU6+YBthSv7tgOjx+qlbDBM/znUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T09:01:23Z"
    mac: ENC[AES256_GCM,data:+NtR4WA7YixZQgiCG2Z8N6dh4+jNZwj5n3+tg7P0civC+i36+VPF4HizsK6fQe6KMd6DR8YSLXg+vEDurjbepvC0qCIRndoxGrn1G+ovF9aoUug2H+Z5MvIlAC4w+wc7jFgvLdzeyoKH7yQsXN9dVFtcqUVx9XGtGMXSwa6P8C8=,iv:itihcmc7uc57RLabZpoov1pivs3Qa5EwmWtvw0Hzs0E=,tag:sR5u9/Huky7qfRl1ZlQZwA==,type:str]
    version: 3.13.0
