# Immich API key (Account Settings → API Keys; permission server.statistics).
# https://gethomepage.dev/widgets/services/immich/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-immich-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_IMMICH_API_KEY: ENC[AES256_GCM,data:ObOEkUcV8XZFdBKtiHXcbFWkMf9uSFv0FEnjRXBUDqxbLa/cl+tLRb/AcA==,iv:ceAe5XDMnMsMCpSIO7NAKzFPq/0LfGqL8D5Gcj3s/tA=,tag:b1iJ3+RHnIVOFu7lPqbDIQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5STVMckNMOEdhWERJSGVX
            eFVNeVF5NUFXYndGLzcwdjJHT0NLZlZDL2lNCldkRzJUMmxmQ1lFc245TzNzQjNH
            bVUzVlNUWFhWanZTRzJRU1lqZXcyTU0KLS0tIGl0Z0FQSjUwWE4yUHRlU3VacVAw
            YUhFTUNrVWpGRThtY3JxYnhRakJTTFUKYZtV0aIR8djZs/oQywtCPV/34mW/jXDR
            fDS3DMwu2COt1NEjA4mkXHvjliKzdiiCbQ0GzVY3m27F6VlUUT/NLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-22T11:02:46Z"
    mac: ENC[AES256_GCM,data:1cbNMI9SZdrLQIliJAAAJNKj9JjcV1PignkaZbX2r4nxpEQo4EEOeKIO30IBoNZiNn/KiP5crfZ2YyhPWPyiom6KwA07S/ee1btQG3N8zPJKELnYWSQPv5sWenp3g8vGtXFCik+1g/91F76bFHILuM3gpkN9wweRG99UOng64yA=,iv:im+P565GyMbgsejHCj1Y0AVFlJC9dNy/8H2tdgOADks=,tag:aohoJvyoej6mRKCXL05lRQ==,type:str]
    version: 3.13.0
