# Argo CD API token (readonly account homepage). HTTPRoute widget in xd-net apps/argocd-route.tf.
# https://gethomepage.dev/widgets/services/argocd/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-argocd-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_ARGOCD_API_KEY: ENC[AES256_GCM,data:I1dxZhYIwRjiEK1YqxMRH8izy8heykiGtH+uQjNiuv/S31eWohJHqqH4LBcxY6N8I3EmMzs7o87FZwiK6I2P5mKfLOjwasNBRnG0gF2hnZclC3xHOj+NZ8hJOEZeu+9vgOFBKAItB1AOSag7gz0QfEN4qRIZh6X//qCXffby6SKI5FWsSAYsBTdkuf3i1mVuFUmEOiAntgoEDexv1Xtn3m6j7LuKpbzqTNqoAerEER+3pT+qjIq04JcO1fhdEkseSP9vc01bmyTETzZHMjI+z8DBSV90r/A=,iv:xnk7plx7y4kCG/dSwCTc1TxaM1GW/nOdzhsP9NZ+628=,tag:sMcui8P0BAZPryQo5nqW0A==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVGlqb3VwQ2hGVDd6RnlI
            UlpUcUY2OVhnSEtVQmMxMndZRTZHR3RyZ2pJCkJNTFZ2TXd4M25yelJPR2FmTkUv
            T2QyWGozb2tJNHJSZVdJRWVrbGRlTjAKLS0tIGdscVJiaDRMN0YzZEVreTliK2pE
            RGhMWjIrTFJyd3RkZ3BvV0V6WkVpVDAKTOJK66iRD+HcrmagtY4hoE8h0H+7W1Vx
            yDx30ZsU/RFgOGQidB3GMau9XYJNujeQC3tFu4277vVOfrkaafEyvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-06-04T02:19:30Z"
    mac: ENC[AES256_GCM,data:WV7Ej/xFDPAbzoNxKnpjyiDpe3Q66T+knLrpDqzz1UrImFZ3rbmUzkJyeAoVckwiSeQlPLBUMm96O4sucKMCqF70ySTI7o+1324o6MYnXhLg8E9Wa7eCbLmk10yO+xTQaPqu96tbZUaspwU4SWk+/+EM7WM6Yi8Pz3aotYTICcU=,iv:xYFqo56Ay9qPIOshw/8XJOqPQkeCAVc/y6wG8ZOIUu0=,tag:BBIFuFijEdWS3Ka+Si78og==,type:str]
    version: 3.13.0
