# Speedtest Tracker API token for Homepage widget (Admin → API tokens, Read Results ability).
# https://gethomepage.dev/widgets/services/speedtest-tracker/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-speedtest-tracker-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_SPEEDTEST_TRACKER_API_KEY: ENC[AES256_GCM,data:kURo2ua6+LCInKQi5OvM+UsDHBmZRcSxlqEByH0WIk5n7D+olUkTY0vbzCrCtO6n,iv:I1CsJ46e7T4lpkKPj1onLasIj+V1L+XgcpIngbj/x7E=,tag:42s2u9R731EkAsc7RPZmbA==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGNKWW00bGI4N3B2bGdT
            WFpjWU85TytqamtXd0JxQ0IvWDRBbjFtY1NZCkJKUVRIb3l3TlVNYXAwNDFSQkZI
            S2ZNMFFGdi80WmZaeTl6VHpXNEdqUE0KLS0tIDU2bCtFbnF6OVltNThPWjNuYVhy
            dDZpNzJ5dnM2UEV3blUwUkdrUmNLTzQKe3IDaVu680JrOgcpLzs/Khta9DRvbEgF
            4S5naZIaXrF38Hc9li27sk0Nc/pXT6vRB7+ym/kv1DRkVFqlXatAfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T09:53:48Z"
    mac: ENC[AES256_GCM,data:PUWwffBJNpBuDVAHRAgBigWmAKnWcdtp5hMlciJFqPYheXiQLKMbtjw8yGI0ObKkd1DROcz7nZdLyGbVwrhh2zEkvj5kMHJRtVk7GpVqiP9xuFZI9kA0FFO7KUMTbbsx4ORQKdQJHuBg8MB3qJyZ4LUUCglMFcE6w3IHuiZo+o0=,iv:OskHl6HA0xb4ULk1SXZX8vDG6AH6MOcIqSFutkxVBhc=,tag:6BjSTpQM2xlgO7ViSXpvIA==,type:str]
    version: 3.13.0
