# Home Assistant app secret — Authentik OIDC client credentials (hass-oidc-auth).
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: home-assistant
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:N2XbhhCyRcKXir5pgIrQQxOXwxKTfJRdpFIe1rfv6B4MV+jBl6AcdA==,iv:oKOfj0cfpNwdXiL64AYayrctzu5CdlY0rqSRLjc5/AY=,tag:N9M7WlwgbCLG3OFrLuSD2Q==,type:str] # sops:encrypt
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:pPexserJVVORzVJ/15vmFPhxj7N+SLVQm25M7JPgg7V9UNvVnsjAQeMdgalG9LpDNDGPS4lXxNGty/SW4Ui6AvzLgrYLmgCeL9piktMldynn4OJRT8Rpm9yeQZYCgYk1LCv7++AmD+GsGJGP9DnMP7DA88hjQzhehmKRFgSKUEM=,iv:aB/JQJ7eFLI65eec2kTtYcTEnhfnbm6s8ctdIMWR90Y=,tag:3hLl8DK9IshyyeWoLD9mxA==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM29td3N2UVRMcDFxb3h3
            L3g4MTVTMGNSQkducFIxSmJDZnRoSFovSm5zClI5NUtLVHhWblZ1OEVuSVN1QjRV
            aWVQaE9ISFFCcUgrZS9qMUplZnlFSFUKLS0tIGNqVnRSY2RzOE1PTkdFejRBSWNC
            OEgvN3N3d3o1WHV0VENpSTh6VE9NMU0KF44qACe8AmvC+g3HHfZESmoqtK5YIc8l
            2f7wJ6/wua+nLU7tgY+/S4DlX8T7Qe8/0akdcyw0Lm7csWN9h7oZVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-06-07T15:28:01Z"
    mac: ENC[AES256_GCM,data:yNFtq7LZuWj4DtI5rkhSC3A5Z7spWxXzWyfCOzotGAFiCLkmn8DSoBV/Vg/j6513WuDlNZsG0ED2iyECrPe1ZLq55ml2/B8Rx7LzpitIrUhKhB3fz3BStXIgGzE8oNNREk5vRKc1ew/EG89+b5UCDlAmkgQ8VdftlhhIK6+yaJw=,iv:lmcT6v3buAIxsmfc60XBfP5yH9sXYSFjK9mti4wmfoQ=,tag:CDzeaWtoTkOohR2jMYglUA==,type:str]
    version: 3.13.0
