# UniFi Network widget — same local admin as UniFi Poller (Settings → Admins → Local Access).
# https://gethomepage.dev/widgets/services/unifi-controller/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-unifi-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_UNIFI_USERNAME: unifipoller
    HOMEPAGE_VAR_UNIFI_PASSWORD: ENC[AES256_GCM,data:O1RSbPxd+E9nKZ6t5d/uiCiL4MfX0OtPPJ+Axkurx7c=,iv:lhV7at/Dn/CR6esbmak6fZi6NKfU9wLaXwHfnljzT1w=,tag:XBLDdIq78gZm+Y4Tiatz3A==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUnRjamJ3R1YwclZkQXlT
            WS92VkxjUG9oRk8vUGpsKzhINVZFSlltVVhrClRyWE1EMkJLRU0wcFpoR1hpNDF3
            aEErbVhUL0pCdlhoTmJXYU1VemxkUDgKLS0tIDFsVmdINERybHNqa2tNYlgyY1gz
            RDEzaWFuRzFwTlJJdVFrU01zZnFKQWcKkbs24XDiukq7n2FcwVFqyJDtykR0Xbj2
            K759TrYJ8mE0/hL2Epma1yomyYwRBCjQq/PXSFOfqHIPcFgE6pCVyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-25T13:45:17Z"
    mac: ENC[AES256_GCM,data:CPv0i6jAX/F3OE/3THzLBFS51RPZiDSwpCQXxG3ceUoyjdpgByjZdo4b3/CANQDYvUw6iDkRVsS//FLURmF4Mi89BsaBOzGQcrHKH7sJLwp6yp6wPd8QYedxKnTbrp4YaPN7bV/QOGW1pUh92NhKtYJsBG8/6zzp7R9rmKrO+Xs=,iv:ThfYMkmt2qPEXzcazwb8eBhyigz3V1SjyEm5ygu5QhY=,tag:mIZGVsW/aiJMSNjzVWquQw==,type:str]
    version: 3.13.0
