# Home Assistant long-lived access token for Homepage widget (Profile → Security).
# https://gethomepage.dev/widgets/services/homeassistant/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-homeassistant-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:/MTDyMqQROkm3l3pSB2xRl8uaqOMTa6B/LYgBeCuj3zDaxLbFcfmbZ60pmMxoXpLgWlZTX5E5lTuttH0cBn884Gh/K3lelJH95u6RgjUbqnvPIxZRiyXpMC+pOjhLSOF/XIe1exQDA1i4km/JIrnJ2ALWA+FaTxTjlfZyde6j/3z9m4U/5TekenEgXLcUXwFvLUPPdGStR/FNz0HryssU9rklTQ4L6ewxuMhBbTcSSgF6l5eC2Bz,iv:/ZN4nb3h1gf9sjvERevNVvtAf9rxNySBVFfgQhFXdNc=,tag:r/gXOCPkciHwXVLUXujZeQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNkZmS1I1MGwzLzJ5N25j
            SkUzMVlmczJGakR4WnlSZjNtUkFvdXVmeW1zCmlaZTh1VGlNSUdKWG5aSmVVejA4
            d2ozM0J1bFRuT0dnT3dPbUpydHpuVWcKLS0tIG1PRVR2akZPcHltWEt1cEptOWdw
            eHNkRytPbGFDRTVhVnA2cFJhVDMybXcKGCMUZyv4H/SSlTrOZHuMz7grFMeo+Opq
            AJwQMo28C3NoF2OEwdJVhepSx0rgRq6kh6z4pk3GiipBxSyzHnVCmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-06-08T02:44:02Z"
    mac: ENC[AES256_GCM,data:SLstvbCksRGLWoPF7eJ/4Q/QSfXBLTLweD2wbFPgc87ncEBgw94BLD26wjnjyYxe3wn7WQMWnu/n8jj4Xzw+BesYx+eip2vIrfQDQxrbO3fLzuaQV0H0G4NTmyBLy7TxCrkXWdvEY3v1Rea2st202BBf013izWviZgHyZCf9q7g=,iv:OUSzBu+EN00MZ/UapSYAEaEetAIxK/rNGN/OmjK4dq4=,tag:GjS1YYlKro0zmTQAzJvRaQ==,type:str]
    version: 3.13.0
