# Miniflux API key for Homepage widget (Settings → API keys).
# https://gethomepage.dev/widgets/services/miniflux/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-miniflux-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_MINIFLUX_API_KEY: ENC[AES256_GCM,data:7QPnXuBr/02/09R/00dPiYHgzwvW0EYIGxxiR2eVRnKzF2oUFfiYskUR7Ss=,iv:2CoNCDjXgorbc57dY9azX5OlYBkmEwQEqWiuqnRpxA8=,tag:Rb23bY+GgmSqBer/VKzzjw==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrekgzM20wQXNWVmxYbHB1
            WTdlV2pjMmNYK3ZpQnYrOXJYL0I0dHNtTWtnClQ0cTVIak0waFNSemFqZ081d2lG
            RlI5ZXFMK042SDhMY2FWRVhLZHR6ZTAKLS0tIGErQWFXbWNGc2pIQXRpamRVSHdl
            dVhCaW5Vc21QMFpEMkJkdzBvcTU3Z2cKZ4qsJBvz99Ete3ZhMtZLXrWrIG3d5OdY
            7yZGAPr4ml1o30KdQtr/cOsGTjaDXdoArc1DSu9sSYueyNwLtLNiTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T13:48:54Z"
    mac: ENC[AES256_GCM,data:3aANtoH+Ub4vfJBSbCMGYWoDy+m3TaXvhDPno9EROjeR2EghQn3aQP++iaSP/H59f9OK+DWcqBIw52uDG8uKf2lN7o8vc7kHflFWPqRMWKjJ0EbbpTc0pqSmm64wW2+hxcV7DdSfVuLRp5N8KFI6ijAEia+Exd2Gk8LOArBOrek=,iv:5pQyuBbsFuvGy0VqDRYznsRbhfPZYCj0IF5EFq6lj2k=,tag:3ndf1D28RCI/RMQbyvCY+g==,type:str]
    version: 3.13.0
