apiVersion: v1
kind: Secret
metadata:
    name: homepage-tubearchivist-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_TUBEARCHIVIST_API_KEY: ENC[AES256_GCM,data:vOZwCAiqMKaH5E4YD3fsEUtcvPiJfoDmTcdyM0VXTPr+UWxmQl4t0A==,iv:JizN9ZnCYLSUBcPxujvqWUy6lJvtC/pAobQfkt7cKJ4=,tag:6nr9LYBwz3uLfhZcVw59Ig==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOUpEYnJUdG8zeWsxSkFa
            TlVZV1VGVWZoRWxpYUpPOEE5NUZQNktxMUZZCno4bS9aWnlXcVMybS9paVczQXNu
            cGpTcG13eGFhZm9kU0RUV2RjeFB1RjAKLS0tIHZidTdnQUhEZVJDYllPcUREZXlo
            SWQ4YURET0hHOTNQbHh0dHZ5a0UvblkKiIH7wYr2ZJEdQMy70Ea62mR62ZyTKr6V
            fbmqd03/+42Mggspe6mLaTalI8dCquRFrHHuVlXRoMA1P4dkx4s/Yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-18T02:20:33Z"
    mac: ENC[AES256_GCM,data:oRD5+1AIUFZUfiAqrdfoYsceeRODtVlNaa4Z5Y8Oy2sbYLoyIKpjQw6oKYuqS60/FTEw0ULS0gxe0up/Q9d1Vc/tO5WCLB3jUxApsiULdIWvH6wbTzzobUeLFHzG6dKhEDtxENPSO9TdBmPjqq5jcsAsnyEnJks/NrffpFp3HyA=,iv:MHKb+GvTixxGhnnPRMs3vv1POmm33BemthVfvo3gEeo=,tag:b/Z4Z/SBAOtRFv8Ta8KNag==,type:str]
    version: 3.13.0
