# Tracearr API key (Settings → API). Used on the Plex Homepage tile (tracearr widget).
# https://gethomepage.dev/widgets/services/tracearr/
apiVersion: v1
kind: Secret
metadata:
    name: homepage-tracearr-widget
    namespace: homepage
stringData:
    HOMEPAGE_VAR_TRACEARR_API_KEY: ENC[AES256_GCM,data:0XO7Afu1J577x+YrS476Nu7XNdiImNrh/IxxFRdxOCnn1MqJIzCohe7ZeyH4sgtF7zu9,iv:U1kotmplHodpc3cQ8bcojuFUg1CEXvpXup3KQfpkyyI=,tag:XJGm95rRvs7s5kblcIN5Rw==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ1lhcEdzcmMvVFBrZHoy
            YkU2UDFwc2QvQm9RUUtGSmZ0Tk9SYmFPK2dFCmpGRFQ0cVJ3YW5ZYUVyK0ZuWXZi
            OE56K1F1QzVxei9TeVFSVnRlejd2bDAKLS0tIE8ra2Zwa1U4eHVSdGNjOG1uVG02
            eVZNYXltV1k1TDNzQ3NIVis5akQxN1UKtPmAmcOJ+Kkb3PwcX9WQ4qWUwEX2a/KP
            +QZRCE/3eHbUhpNurKEASLObpYcZGkdbJMXUP0p94BtNM2TRmtfLLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-19T05:48:54Z"
    mac: ENC[AES256_GCM,data:fvQb9bRoTNk+kJeX+5NIP5qtqpQHgvWyUn+rAsZ7K/Yu/D+KCodgt4nke+4O6eVBp/UBWQgt9Z9ssS6WWBs29ceXP4Cyo/nEflJt7qXORjEBnbi/0PpzwikLUdgvmLnuZLT8G6alf06uk/iFC+0EKwcl2bLDGIjXsdUZfxOAt6I=,iv:JH08cxPs9ftMaRjh6LFNHZSmM//ITGj/sx8gsnRmKJI=,tag:cm3ccsPVJbGoKq1w/zD39A==,type:str]
    version: 3.13.0
