# Immich config file mounted by the Helm chart (IMMICH_CONFIG_FILE).
apiVersion: v1
kind: Secret
metadata:
    name: immich-config
    namespace: immich
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:4QfUKhQrTr0rmfEK3ow7+aPWD7tKf9gdmG2oM+BN4ZNmDh+UdZsr9iuAOCNqKJFyUeJPkUaFgZVDjqC5OOgBmFhCeQ+BB+kfycHCMj7XAwogJygzbaNSUdA9uys5TlNt/FBMSGpCJ3+sw/RK0Vg3NVBtuR2SBlcB2VSdVZO4qhXuCuBkQqtdFjGFQjQ1ADg7MfefBw1fgXOalB/9Dp3VwI2w3yRXLmAD73B+5jlnoymmM7vhTDVXqOKJ9+OA32fmoHCJi4qtEiOeKUwzDza3XNrwhV11sorNKqNn405OodPAWHSSlSHf3FKEGdIaFkxk804qIF9X3aOknBa37wrfKwx5lSkj+6LPMaWkReIrnj+Gxq45KhZS3BjQrzlUuiNYK97YUJz98ev6uFaOg+rio2JTEn21dUN30cuTXpuxSzmKsPBJPePsORDFRnVuyJLHTFGwM3JNTFOrUGo29LKP8Dam5zifFLVLfqON+wD8R5476lrsE96lzwqJjz+D5i/XlhQsL6NMnHP26Rkm9p4+fMgX5Ph4IqFAdtbCYDYXS4jFzZ6hn0ujeuJFXEr4WM4SvqJT+whdFF79DQPDFk6HHXDW1donkYs/5r95FxUlvp3De4T81QbM/vtSpbN1MmRtIaN1MacJGLhQ4oxVFEDXL58Qbr1Ak+VRzxg3XBu4QkvKXTYORSaLUNSCpy/DM8Tz8szV4aDmyM8lkQG332pJHDQ2/2Hd0M6ZICI0mvBKadMnR5v7HYBPkLNlNQNxBVXFr1Su8O0R/Hp0QABh9V4S0osb1YZYge4NJAdMuIOMbaZK0+E4koCxArxeLpfL9VwS/RL6osa42D7TfagYHGKzltiXZwJRW/a7YsFrp+NkyDT4rXhQqY15gRmxLJxz0m6ZucF3b17Xm5odWjrUbuQm2b4vqt2u3Xy6A4L4hBwvvI04y2mo32CM9YFvINWSwMPIloN0uE3U09LKpVq3aermagUYIG19n5AYgIaOA2MM1kWQek6UrZ6WspC6VLPvUw+y3WUJKIVpAWMGQsMSokjpSk7qB3Pfqskx3/vT+P1Q5k6Gfh1XXU2cp7Cw5LnX5ppKWrPt40FAvnP/bP6jK9T+V7GeG38areRO8/6KOJUqT/PAvvKrRwrZ7TeQxt3jmcboxlgZxBle/C8tefER9KmCxg==,iv:V7wC7zqGh+GlMc4sqaXqBaIc/lbTA21Os2deRPgYLuc=,tag:E232xMUuH/hv0TxGmOsJWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVzdNMEtSTFZRcnFuR0s0
            ZEZ1cWFWeXpsS3BldnZlMS80OHdFNjBLbUdrCkZBSkp0ak1BOWpTWm9yZFJlbVpE
            V253VXlNMnFzZE1xT041WFpCK2ZzT0EKLS0tIHN0Yy9XMy9WOWJjOVdDR2RkbGRE
            SHNlektyanlGclhqQU1HWWFKQXM1b2cKjj6FI/4a8nZ0IcNXQkAkikOj5PJwwa5a
            B6EfILyuriELki3c4ObqcuqY7uneayM6XVgCPlNiuqwGJh+BLB3xFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_regex: ^immich-config\.yaml$
    lastmodified: "2026-05-22T13:19:04Z"
    mac: ENC[AES256_GCM,data:3X+kzhtHCHoL8MzeE9rZY/KXZIJncxh34HK9kfdPjk4BNTA6oKnexvbdftZznBNdq0tfC3yx8wSAVc0Gpdl3cpN76sMADyDn02N0Qrk291Uvg1zP1b8Cr8K8bVl1q1ki3ZnFqVebMxC/5umUD3hUo9ivAYTI+Q8tLeRAjqsLxks=,iv:BY/T/OnY6bqkEvaysDQZwwrlf0C+WwHhqyZZVaAwVRQ=,tag:QX2wknaERmbygbgto8WA1w==,type:str]
    version: 3.13.0
