apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: immich
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:s5lyLThodC6iX2SLYGj7/uKeQNbYCLRV+4U=,iv:RU6Ug8MdkGlC/DbwfvIqx2qJZSimjabX/Nkhk1ijWIY=,tag:4Di1cw2sKa4rrABGFc4+UA==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:stQ6aISrTzLcGu4ia9wOVYYTlV2QVl2ZfzWcgOjggpgkj+2e93QaJsTZ6Wy/t7R9yRDKGkyhJJvOo1RzfprNUw==,iv:Wrv6ihJi/Dp8It9PXmdwYAwyK+8Gxl3yHpC289k/ME0=,tag:4aMftjsRLI9KW0DjgU4WSA==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWEpLYkRJNjJHSjBRWHpv
            UXNVRXA5QTZFRU1CVW01TnZramFYakhFWHhBCkh2RkJrLzZVYjYvQitBcmRoS1d6
            MCt2Y2ZPdGtIUGowMFlrdFd3dGU0VTAKLS0tIDRZZ1lqcmVrcmNHUWp3MGltWDlF
            Z2RTV3Y2dkl2U0pOWVhVWWlLclRYNkEKljK4VpBHKDsy4Pe9+D+G8ug/zS66q09m
            27UH3JoU9Q8RjSblv40fICJV3p9LOoGXgce517Oqt3rrSZ5Unmed0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:qUVlmSJMb0leSUzAXbe96SaiLa1HFw2eMQGgVC3Qzz4LAG19DJ8MFvuyFDzULNxR0TaIpJOIjikm7ZKMEetf1Mf7UWiZ+CRUqVnmmg9kkcR/mUQ+89FeCtbT3S1ophgWfvZpC2ZIYO+HYWSH/PCU/zoIdXd+ttYq4BASIiHyBTc=,iv:bLuer+WFG9DBgsjZSHBEiSxrwU8GXmujalyEflY/L3s=,tag:0v1RugUShME1Jt9vQEBLyw==,type:str]
    version: 3.13.1
