apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: immich
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:VzxOylY2TttnxVKGnrjbed9LFTpBOpI167s=,iv:E2MDI9dEM79QPFmXPKmtMULeGAqP8L3Ky18MRst+EUM=,tag:zK2O5MShCzZQQY1IT1ilcA==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:KGt8JEFoUmLwCQOf0K4v0zzj0+gnOPX+k2cA7A3trlgnHtLjTp/fnYy7gnMGR8yVr1/9pVid9GA6nmrhohN4Wg==,iv:vCT/sx+KrlXPOEBAgMSMNqeqitCvmZSeiIoPFHwLm88=,tag:p5K/GsWIPFNggIRrlhA/Bw==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbiswSU5YU01vUnlwbHdl
            TVQwVTRpVkFna0Uza3dFUEtSRnVWbzBqYUhVCnB6VzBwcHFVSVV5dUVRalNSQWFp
            TmNKRjAwbEJRTENTa0VqOHBpN0hBK1EKLS0tICtGNHNjcFJBVjl1RDVkK3lKMWdx
            SDRaVVlUeFhHWXNnYkEwWDNMVGw2V0EKDJ7Qg+chFfoMa2hYROc3fBHBAGjzlhZZ
            dYiHQK0eaVkHHh1Wz00rp0bqSMjgFCuyGX1Of9eL5stSQdMraf0QBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:nMgSYd7PmQat95erZeXmTLpFxCv1gc7EVUgbJJnf8KpXqkU4JsGLtgExfyH5qZOE2UJA0QodGfyzcYQg2h51k5QwAd057rzqICoYeAnX5UFQkhbsYLNzN6OZoC7lmA9TXVjwIZsoRDD6JOAxP4OLfNCG5IfMD1Byz5Nc+SSDhns=,iv:albpZrnKWwlrDIXUAn8/1PLjsxh9f51QTDYn81E144c=,tag:hnTCUtp8/uuW2Cw6JKpPPA==,type:str]
    version: 3.13.1
