apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
stringData:
    username: immich
    user: immich
    password: ENC[AES256_GCM,data:tR/a7SSpol7XnrnhRuQ/ZbAtC7gsod7aUjwux6aKvwY=,iv:lx243l9i0Fwlr861eNxIcmrC9MIiefMXGyC2aX9G4Pw=,tag:5tUdXvJ5zE0R8IPHZc8qPA==,type:str] # sops:encrypt
    host: immich-db-rw
    dbname: immich
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBac2VYSjBpS1RxZ0orZmJy
            NkJFdzh3b3JuL1hjYVNCQWlyazUybDVnb2lNCkg4Nkh1eERpZDhZUmZvNjVLWXo0
            c1UxaFlOdVU3d3ZtZ2J6OUxyYmdPeFUKLS0tIGNHRkwwYkNCU284WkRCRHBWZ1Vv
            QjdUL0xLL3UvNEgrM3lVQVR4RkJrOGMKbJJ8x6iERlQg8fCXOxmbpuHwEojkUJi3
            QZs70fqKEIbMhEv2kU25j4DBoziBoqBwcMwKf7qsU60xY9htTu1RDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-22T05:40:25Z"
    mac: ENC[AES256_GCM,data:su9a4ny2MAMS/tc4Qv181jw1LiOIEweg7wuj/sKfKKPf7IfDzNMr2ICOD0Me6eJZl9yZMLQzUG42YIiJkGUyWFpGycyDm0OZXOOCIbrPh2ZTnU5opJmOTGCS0s5Igen+ZzQt+/qMcQlp58tVptcwG7n87hy9GxDoXxnAdeiTzEc=,iv:zauC3koy0CE5Vk90KyWulyyTr5IkXAbqJmI3velNXoc=,tag:t3Rck8igL3i6twN00o6Thw==,type:str]
    version: 3.13.0
