apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: invidious
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Ov3T83omQ4p5vULV7wGVsRYnhu09O/fpsxY=,iv:Qlu5vBoVEqoxet7QgTKxLg9Efjy74mpaseNrMP/sTs4=,tag:i42+6/BNZGI0eDxMpLQOjg==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:bpqk+HLPY7t5murfpYSgItQ7jkyzTJfpmRo4j+V09lhcrMEoRvr8RSXN+uCDTWhHgD7uZaJQaHR3XaVWlfXN/g==,iv:Y3Ljt+f5a5m8LXN05EAIBf7ZHFpS35yEsFW2djGVt78=,tag:upJd9NUPC2MeMg0VlCGRMQ==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWkhUb2VxQnpTRjF6Zklm
            Y3hSOE0wNG1iakp2SzQ4RnkzR2llN3lhc0RJCm1CalFIVWt2dWQxVU00cmhvTWdS
            dHhEREQwT3lkZWNoM21kblBNTXBaYmcKLS0tIFpwYXVVTnlCU1dxTlRaNkJIY2dU
            cUVZMlRyVWx6eUZEWnRWVTlmVzd1dFkK9eIYFSLhuN+5oc0EZh3xPPSj0FzmV9u0
            kKFL5EZc5jzToyrD/EkFgEIkaxJrkPj5+8Q+LMfuQawD2KHpPD0bxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:dGyec1I8zTu/1Q7B9lZSlgCbMpBxYPA0ujnB6P+gUTfa4UBkSKOTqlRVh57OWCt0AWaVGRnw1TUsc6cgKstYNMm17JIw9fgvKrgLXwW1t0pPTrT9xOFoHUMxzotedVNBkHfAHtAJ43kJOb0q5rTd/AXBnxcejOLZqJwcj5Yt/FM=,iv:4ekCOZ3pFqsvwrAB6/c6s31EmUID+unpYgZ6dGDLvhg=,tag:IOFD5u5b6LVa01uSrRcj1w==,type:str]
    version: 3.13.1
