apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: invidious
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:LBICfeLZpITjEycG3X6LTBLVf0ZmnLM1CaY=,iv:ZmyxLIIAl3s3WNfwPY/4u586QbTWCZSCEeTeBh1Zv0Y=,tag:aVXeNFDijB4AI6L/gH6E0g==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:lQqptNF151oBNqNxwWMMn9yCIWASBUoSpQvdvCDWVsKjQ6gX4NYlIJ9frXlgy8E1Jk02qJi3L35pu01mms6Ypg==,iv:9eryK0XAfrxsm24N8SocfX3tr7JypWPfCEoJHNj2RQ0=,tag:YognvHPMc2eAnUhZvJVX7A==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YUNSZC92d1JqNG44QzBn
            QXB1ZkwxWVhqNXp1NlFUUktEWUFZR0ZNb0QwCmZRdmhkN1QyZWU4TEVMd3dwRFd3
            NmJXbUJJbHJTcEhaV2k0KzFSWmh1SWMKLS0tIDBHcWNvQmJreU1SSllZai9GUkhl
            N1BISTZOU2dKUDVLWXdZbk1Ub3NnaGMK7NiypgO6Q1mmmrJ+JN0QF2r8bFlnuz7J
            yCCBJlHz/YxDkKfWAqbjusivl9SIlZPcUt0zCy1yeFEYEZir6Btqag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:aq3pLJ3f5KZR1kK/Mb8T6PgyGP+Nxd/NDx0gcl31/vBs7JHskQ8TkyNlDBUllyWZuBRdyijyoVkEPtbl7qotX9hU9cQbXMmbtSVvRa2WwQPLmvn0kBnXzDuO5/JEfEkURbyrIA9clE3enHLaLH9QWiD6mrv/NseNo4U+QroBmic=,iv:oYfTtwJ/W2PK4516IKXCx1OlBANByvjKLf7o84rgPPs=,tag:NjZ8Xv9lGlOINL3c14lRsg==,type:str]
    version: 3.13.1
