# CNPG bootstrap for apps/invidious/postgres.yaml (owner and database: invidious).
apiVersion: v1
kind: Secret
metadata:
    name: invidious-db
    namespace: invidious
stringData:
    username: invidious
    password: ENC[AES256_GCM,data:DDE6rXFUkA8gMYpz453sVJ9cdmhs7f4v/WVb398EpRSdftc9vpDn37nYpIEyg88c,iv:EhJGHi9aAWtdZSuOk0OR28nK9i6RBppwflFQj5Ze7qQ=,tag:aJhbv4XxYqF59chwVrfLZQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZGJlMUQvWUNiSXgvejBj
            eEJWR2ZibGJacjNJWHR0Y3BFWGFXaG9UUDFBClFUY0lsM0hSTUI3REVLUG5MRGoy
            Z0xicE5CbEVlYVNMMS9CdDVqL3BKc00KLS0tIGRCTkdGbmM4QWwwT1MxUjhzNFV1
            UkhFTUhJSlplRGsyVEpmTEJnL1MyVGsK//W0273Z4MU1bVIC2XHGaSZHPszjXrzU
            JGxaZw0RwxXTi8hBd/NPr+IMjNgZr+ttC+dn42kXx3x9OH18CLsotw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-06-30T11:14:51Z"
    mac: ENC[AES256_GCM,data:p58XUMuEKYvJbynunGgs4hnmAbifJe/vHZwdymUU2y6lNEMtvenikiBwW/IFfU/wf54sOmwFb7EXKLsRt4fycfHRrx+Yvi+hx75nioRHAr3GbyYzm3o7sTpuhfPT3/Z3Gb74may7QRZiXezVJHLMCSWtbw57BSpxOIY4y4B0C1A=,iv:eXo+0OavKqQ/odxp9AIuoBExLgnNrZZ+guBGnMg1jEQ=,tag:PizCFwp/6gZp5wP+/AVTuw==,type:str]
    version: 3.13.1
