apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: mealie
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:NnNM9nOfPLp6DZu+R0pWdWhX0YZc50zZN3U=,iv:uYP5Uk+Bgmt4jyplvkY5k/ODjUrs8pEjr9zHNpFcxus=,tag:iLWIgnQEqpcytepZXmKITw==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:GuKbO4fdBCA91WOdRO1mf7Ok3dra2Oz96NfJn4VufBrYvX99OXGKhRrWPjDE0sYr6TLdz8GzFHU4MSiRyIh2Gg==,iv:u3l3loSihD9rCbGYvwUx2zjkSVikh2pxnslK9O3f9Kw=,tag:R4ZYZoFLnjaKkiEoeHjvYw==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Q2wxTmZGQ2lEOGhqSmR5
            RWV2UHhucVNKL3U4RUdKY0x5cmJtcitWQ1VNCmMydzF2RlFFVGY5MStzbmRPa2Zp
            Z0ZhUzg1QmZobVViM1VZeVpMbjlScU0KLS0tIFhHWE9IMUs4OVlaaVB1R0FhY01h
            SG1UbWVaK3BINlJycHhvUkdSWGxlcE0K80Dc4sEScFxWwwj3QhmDt9SMd5rwAWXC
            /k9vd8lpyeoIuVQ4N2T+8vQcPCoM31jQID3oN6B2pobDUVX01W7SSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:09Z"
    mac: ENC[AES256_GCM,data:fE0x6Z9UFR1fD1Z5vzoMmHwGtX7gvwRYTI+I9pe4yXtp8y4E0PjltvJulTXaXa/GwyLf+gCVyAMdqCs5zuffiz479iRVZZ77uM9tW7ryXJAKFM1xuuiKJqVa7gMr1SZ/fLV6ErFv8EBQtgfg/VkxI2ZHsbQ6Ic2ZIzxt5DVg3+k=,iv:61A0nQluNlwUwYChSbuICLr885hvZJkBzGVfDUukpBE=,tag:Q2tOTMTdZdF4APO+mDwhhg==,type:str]
    version: 3.13.1
