# Mealie app secret — Authentik OIDC client credentials.
apiVersion: v1
kind: Secret
metadata:
    name: mealie
    namespace: mealie
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:xeuz+f2kTRbEhu9DF/2DXcHi9TeBXYT30IyO8hjcaFxVAPggaEPIxw==,iv:LSWNDP16OoX/o1ihWs1C8sArnAzkH1NF049djxkObyY=,tag:6NeGIab1ezK8dm2jdiCDyg==,type:str] # sops:encrypt
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wDzLWACriK/eBDueq4WqgFVfOx3UTIl56NOlnO9qlmRnN3HPlP8SBtHXtLNgYnvT7m55FnnEL1/5KHwNWNvtlpaIB0ivKqQWGZpC5UPkNfQxl0tz865fmouj35XDRGRSXXqkD/gFEUz8VJaBLlcqWUer3zNvQYbXu2FNJKuCcAk=,iv:4MXywEM2TEtQRF0DVuaIAS7prtYjv3Ogz9GZw9yTvLk=,tag:zwVudTgOApaOL9EHHnmFlw==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbEF2Nmk1U2hZNnhSMU0v
            dnYxenpUNXg3MzVSZlRQSHpiOGJ2bzBkL1NvClZkdmIrK2o5UjdUMFdGeGJFdkxS
            U2ZCVkN1eEhRM0JSWWc0blJUcGR4RWcKLS0tIERkUmhqeFFVWVF0UEFHSENzdWJZ
            K2tKL3BHbTNWQUdKVkRUeXlEVWgyK2cK2+nnb+oyFtRJqm1ZRm3agBP7zOpxnWEY
            JX+jU+lMIb+LQIAz55Cap71R7BsZRsEMmIiyBiJHYspxUK3TKdM8Qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T13:48:59Z"
    mac: ENC[AES256_GCM,data:SHvjLPgUwWDZt6E1NqM9T/umUVW71W+na+aZ+vK7am9B9vhrwZhCVMT7ZYPpbzYcY996umBcVKn5Yo6RUcHAdb0KPQBEgEIalBqg6ekSHVizBTqL9RLwNSTFxS+ONguPmwaQO+1FXxZRuLvndXotUeDHQ1DQ1r7WCuIDqf/LIy0=,iv:4bLvuftHkodZnnYQogNF/fmkMFgcgV3E6N9Wv/u9HWc=,tag:T7rS93inDZZbcsc1UYkiiQ==,type:str]
    version: 3.13.0
