apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: mealie
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:iYqZwxizVrkm7yA3qsI5HmalcfnbN0Pq8K0=,iv:/kTVrkZGeyCw8n2bRsietlz7oyxzbbIHal4cw3BPMRs=,tag:QDmdcADZPWwgzAaMvsZG2Q==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:01HBDTXbCI2vwBGztPbPBCcU2hCQ6PafnrC99OvUqb4TufWndqHs8KUDaSfgIJTUNdc9FG11iN1S9WZ6FlU/lg==,iv:MGPWgPHW9io1Fc2LxtxivUNfQD7TtLXKLfEhG1i6u9g=,tag:NIOI5ipVD4Ek+DVkAbmhSg==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUUdNenkweGtMeXFOSjJZ
            azl1Zmd2UVlnajRpT0loOHhrbXJqN3JCb3pFCnd2eHhMNXRBUWI4c3Q1Q3lHVkpv
            RW44VExaVG15TlQzWlYyZUh1KzE3S28KLS0tIFZKYWs2ZGJ3OHB3cUluVUcwTGhm
            djM5WFdxNVl5U2QyTXBVQTFmNFNlOTAK3KQaYYQWFK465KhKq0cXegI0mDwFXdxY
            LaUY5XCuuFFQqmga7S8HEJa9g4wuciKFby6SCsa2MFxxFwkaOUsyhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:GCQqwORDisbUYk7p0VlxmOpQx4K9WxTQY6i+qM/HlrfpAFbRxjHyyzbN2Ro5D6KYzIgfwJVThbSmR8OdDW4l+Ll4QeToesUwfulq8oRb/+87feD2g+PAX5D1D93Y2Y50/7gYhU5NYpqg58Vi0WAA3IjvS6m+0E0l4RUo8VRz2+0=,iv:YikA1pxg53o+qzK640GbZ3tbbtq7DkwioKzVVWDUpg4=,tag:VSY6CbMQeN1e6XqW6cFSVQ==,type:str]
    version: 3.13.1
