# CNPG bootstrap for apps/mealie/postgres.yaml (owner and database: mealie).
apiVersion: v1
kind: Secret
metadata:
    name: mealie-db
    namespace: mealie
stringData:
    username: mealie
    password: ENC[AES256_GCM,data:TM8LI/egS1rl0fW97XRXEHjSJWEPqw636heVON/LztE=,iv:Z5xOQLvpLvuHde8+t/dYHlKssQj9M+KoCt949ZlbOYc=,tag:MOuhGLWKFcWbBPxeyVyGZw==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM0dSajB4V1VyS1ZEcGxJ
            VytPYVNIek42VVBnRyt5Zlk0azJxb0Z5NUZjCkxiU05zdDlkUUFUakhoVjh0UHZC
            R1F2OFp0N01VKzFEeU1tNXRYQlZCNEEKLS0tIFBIdkpudDlVSlQwQmlOb1p1NW1u
            VWxCdms2bFFWVEZJV3JZTFdFUnd2QlEK5/H+WDdoT2ejcQlo4Q5jpcagg1MRhBia
            P3nbQ0aUORIucwrdqqbkhV4+nNoGDhS4yfRKjZfL/an3Q0vBslzaOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T13:48:57Z"
    mac: ENC[AES256_GCM,data:fHBVojkG5PIxlMW7HQIAN8azzC7eG8wM5ZPH0xlBpSBsJh9HwVDApZprwYjd8U+PTRF2HSIvba7jFTxR/KlkJ643As0Z0uJb55d36WPjlDMuJv2xrwtGj8XW6+8gbZD/gtFAFYhYsgsf6zekri5TrSXIebAOrVmC7q5B1ZwYeIk=,iv:KoRPr+VgEMPOZlPnany9uZhu6A6/84NgObhpQmFUR2U=,tag:rvwgrGo7pMupHsWsd5Q+ng==,type:str]
    version: 3.13.0
