apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: miniflux
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:QrBszxvigrVB4aUroUWTk6k38L5IOKvCQp0=,iv:ziAwA0N7Zo26KVPjHpRPOFIdDb1r9PTsc19RurOZoy0=,tag:8ChqgLjDTURjd0jEy5UACg==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:QilYnYmD1rDYyqmFWFL6bgTrDa0I15os/pVjpN8Ki9w6X0xyQ0aGWh9eme4Z+z0ll98jVFRnLjpeWNKO4TpAWQ==,iv:FDKcUZMMNa9Lb60TPAAjyJYIHu/icjHbdJyeKCxMbZ8=,tag:yrfDdjsvsvWTBBK4TNBJMQ==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGQxQlFkOTUzKzdmZFln
            cGE3bFRmWDkzTUNMT1M2S1l5YzlNRDcwc3lFCmZGWU82S2dXU0JNek5LSm1MMG43
            Tmp3Nzc5MnpsbjQ0THkvTEJBRlNWMEEKLS0tIGJrQ3p2VkU5bUF5dWY4NEduZDdN
            RjRUTHgxUE1ZeWJ2WkpVd2tLOGtKdXMKHwgFuQFd9HvifiuqGwNGLiuLynDko+22
            qXlJuT+S/+Yv8a+L6gDYFFQ0my85Tzk2jopTPTvSnDG1jBbE05HXMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:CZAGzOti099uMCCt47XkrKBiYV1JS7/HcRDnDLi1K359FU1Kt0QOrTemvws0KkNx7y2BWQnLc5QP9/Cc2SqE25hwSvMIPTUrjFofhgr6St80oAgH+k1K48SrR6CqcETw9+Ce0P3geM8SbV7XU36zCm5sv3wUNpzDmB/1aCQa6Ks=,iv:XK1XonwEB2yYy6+o9tvukqJZQz/Kjgn7cfmZ0/pyPdc=,tag:mSOQGr13PCK5OhFuwszMgw==,type:str]
    version: 3.13.1
