# Miniflux app secret — DATABASE_URL and Authentik OIDC client credentials.
# DATABASE_URL password must match secrets/miniflux-db.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: miniflux
    namespace: miniflux
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:3RWzzSwfWGQ6WcwP5+lXhi/gL59DHnQHcToKIPdTJQp1xfwQiuvLbg7WMrtlo7gUwV6EM0087W3jP1TFdQGNuU18Ho4PNLRSKUr5lbnnu4PwZC4WVWxwP7t5UbY=,iv:488HXn+HLxIPpkz+/vWQmrwLc+cyoJog8dtYMT6MCro=,tag:4BGWrXqiLcUgwFRmGhP4oA==,type:str] # sops:encrypt
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:qsCdeIF4forNG5I+NHnCE0zNU/5PjWVJgmpO17trhS6RYyBD3Xl97Q==,iv:DlYZtq6cjwfBhPxwAuoK52ebnK5h9MjefMmKI311MMk=,tag:ztrKALL7f/3jRwe/M3e/OQ==,type:str] # sops:encrypt
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:1YyaTmTRCGdRcpdRPcrgJymcEdqAzHzN6L+XcKuxeEx+pXLLV8pffU26qOVeE/L1ukORsPUqkoA0Z1GgnBdyEd7Dc6MxRLrzKRnfXnbI7NME5yyjenxnW3Sm6Q5DoixtwNPDKwIcG3cCVAELOyooUenRKbNbi5pu3Gr4XpADIBE=,iv:YYMOby+w91R3K88pfR10t509uRGpFbsWL1JYWFHpr2A=,tag:cGwp2zgzU3/Iwa5rpSYEzA==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RUlKQjV5NW5GcXpOSHJn
            YzZvcFhNQTY2cG8rc3ZCUWdVTVlmVFk3RmpnCmc3K2gzRThCRnJ0Z2xiTzNKZTRH
            eWFYS1lsNTkvSlEveHQ0cUtGQm1nNFkKLS0tIFBJOFZFYUozdnJubHp3Nm9lc251
            czEwTFdSOTlSRmxCenYzY2J3SWtKY3MKsQM9AWiVzUcX6LIZG84yBqX2Fgp2SKZh
            G6scqHpWiFTsnciZYbVOHtsPrtL4aGDaOuL38y5I5sN6CGntK+zIqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T13:49:04Z"
    mac: ENC[AES256_GCM,data:I0NgqCytWh50M/uLMM7eJZlwEj3CH3TFa7+FqmEI08+3Ogpwh/r4War2LmgXpTAovOVPxnGLEFSR8viCMf0axipt2Bh9czKQpWHMACLhg+t740+ibSHDEbfSsrMQ7E+HNvtgvFmVdIhAfQSwrfwYripdpPKB0b8+3ZUmU2hZF7Q=,iv:yAE9iNspry2YBBnQZ7iPi5ZMyk0KcJb+MaeUBJ96p9s=,tag:xqs+S9PDQQg5XpPzuJe0yg==,type:str]
    version: 3.13.0
