apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: miniflux
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:xpKhMp7wVwZqU6YNd2Fmna8BZw/Dl9Rwa3w=,iv:jU0HJ1xNsVPqVFISaAyJymhT9h0W3yetVm3p4cAhdik=,tag:BAcOzUYE6qbJBMiHXyyf2w==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:CMjrvatQbEG8NvRsCBxgFk21Kc0vUv/rbcUP5ybk78fY82DTMMEvaKXbqo8d0A95nHbDXJyTFHfY8/haO+ljpg==,iv:NRupQIIvEXqPXw1YgDcvkBolH3kzko6nYN8qhlsKcYw=,tag:E0KHc23QrjrsfD9zRwsoVQ==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaWhhWjRpVTArdXJiWE5i
            eEpsNHV3TzNuNTU1OFRlemNJdzJwRWtoeEh3Ck5weUFWVHp3S21UaXRHbEk0Z2lp
            eFVIODBMREQ1ajBQR050RVJBMHZqOFUKLS0tIEFIa0UwcHdPZ0hWTG9Gclo2VlhB
            RUdlU0JxOXphOHRlOG1qOTBDU05qU28KxOfwqDa7qGgCcrIAeFWqKG54Esg48ISP
            HS73JO/DBSIEaMg6RRQf+VwI/7Hwas0dB0gMSJBBzQAw12iTxD+oCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:09Z"
    mac: ENC[AES256_GCM,data:EfjHPPa39fvoDogKXh7knTL/8BVS7T3lT03/Fs6qNMxdSf77GmsUS34AtZ7XptJ+0sodqX/PqshnmjdqzTYaMTj7zT6DXuUoCF085AWDOu5oqykX2VMlZXGx22tjNovBkamR+VyfJkhfRHXyQ3SfTlLiHzlonZfJLMIQhxhigoU=,iv:jO4x7moku/Ic7tdo8t3zVLACCwCjciHiIB3iLCD20+I=,tag:Bk7P3hhPlQdWkV1HYaRiyw==,type:str]
    version: 3.13.1
