# CNPG bootstrap for apps/miniflux/postgres.yaml (owner and database: miniflux).
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-db
    namespace: miniflux
stringData:
    username: miniflux
    password: ENC[AES256_GCM,data:LX+uJyVsvfT/ICURJZcnVJ9cfcng9uAdhrRU,iv:5XFaGPcrSTrU+dCHgxCk1IGRFP0CEXcngpp44SfT01c=,tag:ikSpbW5pKbmcN9bDt55H6g==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUFFpQlNvK1hkUHg1dHk4
            cXhtNmhISWFHRnVWNkJLYjhQa3kzZktHV1NNCmh4cTI4S3BST1VFaCtlbzhFaWtR
            a01NNkJhbXN2eWJiM0pVWW1NYzh1OUkKLS0tIFRaWWhUNHFIUG1BN0hSV0lOcFo2
            T1FxRVNIc3Y2dVR6TUFWMEhGWjZNU2cK2AK7yTZhQydd9hQiShhXW65J3DMsmeVV
            0EOfu9VMmXQfJK/fsCPayBJ1naSlMokpERgZ882ml6+A5QVGZVNDlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T13:49:03Z"
    mac: ENC[AES256_GCM,data:D+vfxWDIXTuWAET0cYyo2K4H1LPCcdOz3/i9bjvwwJTEQHmQ9RC+U7wUINbFOT2LVRX7wqAa+fSm2AuU28IRgVt8fYMsd7N2PahwheOzAE/x/XIIEN4B3OV/wUP6LhymOsuVJ3uTKDNtaG24NmW53fO8trdo5erpBCjx7nQn4uQ=,iv:UYtihK+jUD4UwkaVLXwU0IJvA+fIcgyhmbkQTYmsGM8=,tag:kOfny3zrP3NeMWbIO0yygg==,type:str]
    version: 3.13.0
