apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: monitoring
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:+vVdylkoZrwwGshv1eqTBlHHU0kLgqSJkmE=,iv:EP1izYrlzCL2pgU9UFKhTxTs2GvUfKPAOrHd6KQj//4=,tag:zux+HVKO4ciOuNSlR9BMAg==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:lCtJ4Na2SPIK7xBIPUv0Li5vURJ6jbmfc01hXoyRex74kRiyZeKCr9jFQCoJdH1i2mX46tBvuCofVD8e4kLBJA==,iv:VeurNOhRZJKeuZAshcf6VJ/eoLH5xWzPIr/SX4rSDSo=,tag:HgenPdtpjZbE7qMOWbf8+Q==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcERFZFNKLzgzTHpXUjdN
            SWFxTWFXZGhmYndTYll6MXhvMVZ2dzF4dkJrCmNFdG5nd0gra0Vab1ZGMzZ1Qk5E
            OHlJekhabk14NzNiTUp4cWo1Mit2bncKLS0tIEphaXhiYkJXZzJSekdwUnVDTkUz
            amkwcktUN1M2eWdNSUhoQWdLMkhnSUEKDqfzqacrWF2AkencTBYDOnwsFFhI1DbE
            VMfkSAvPK1xuA4DKAIGZQtDfvu2fzOrvkTeuR5jS6y2ePHOckDZpXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:1lqxu2BJwmpKLcHHoEtX4vEON4IoCON3LcxLZhbzBklqlPJD7k0j28BWINxOr9AYvaoOSwFHBMsxQqtvPEETZBaxV/lx3MzFHBIjUClXaLdvfPDH1T11bUUCaHoUEoBd/czg5zlGfTzRhuENLlpBGT58c7sKcC4K48XLEPENgu8=,iv:GuGFy13eSXRY9gKtP28mFAkjF4iC3yDcR79kLVtVujM=,tag:OfH7YpQm1a9MxPO1h0/iLg==,type:str]
    version: 3.13.1
