apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: monitoring
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:aashzZTez3FJv3haJK7pnW+8IEsHxagu6JA=,iv:3yx14fFV1C8k6OGP9oOT/+IPbW2q70cqsGRNesjKejs=,tag:dij89pWkxQmws4Y+ujuz4w==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:IHxCSzF5lO3IHhhscVNEFzRQqwRI7vTfl4WKUOSMISmUZ+6Hm/hltA5w14wD1GS9JNt2GbR48AHI1cCvDQbJZg==,iv:A3ECmDjGQOixRTrz/aMNtOL/IM+ruK75zo10++22OK8=,tag:jGxKC9CYs+pyT4K28fGV/Q==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4amx6RkFpaDhTd0N0Uk0x
            WDhuRzRsQkdJODJxSVI1Q1dySWY4Q2dJWkJFCjFFZ0EvRjVvd1RZOS9yeFRZTzlI
            djl6Zk1GRHpCRlhFUVNVUVFQOGx6N1UKLS0tIEFXTGh3eGVjNGsxemY5cit3WVk0
            Vkg3Tk5mWnJ3VXorYjNsS24zbURpREUK/ejDCeQhosmG2ITcPK59xttebuuFLCl8
            hI6Qp5zS6t066ssDx4maj3EGmQqfnygND5H3EiEPlDM79QarttjPhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:FmwsxilTnlsfRDAOb0Hlf3ioFvVcytbh4aWjbjiVDVlxx6dobPr4Q45zj7qXeB+xfswM7vxCMcd35QeTcwoUPDewUZW6nrxaZ3zAQmTdyo8NFjxdc+zxGBZG158xcjZ3r1pbQO4g38sfvRlaPnr7SWY1k9ikZyo1+j3wFtkvU04=,iv:tjWOPdLDpslaxA8eIf2GRa5Aeu58gXz09Mu1axNMjOc=,tag:rsHVUsmOwIqojHXewIk6Ig==,type:str]
    version: 3.13.1
