# Paperless-ngx app secret — Django secret key.
# Generate PAPERLESS_SECRET_KEY with: openssl rand -hex 32
apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: paperless-ngx
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:W4fJdHhn4Jq52o8lwsSdkQVu8iyTcqlTAkBFmwTcf+mWmd3l5D7/wZ/EcS2w0BLg28w=,iv:T1274O5Hc8a5i2qIaYBw19fymwFZ8Xy5THhf5Ze+4fk=,tag:UFzSLEr+ps+NzPQ3IJhZtg==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVkEvbGhEUm5rSHdUNzQv
            bUsxdmRIRXA4QTd5Qm5FbEsraHp1bkNBRTNBCkMxdGd4ejBuenVFTDNjU3kvR1ZD
            SSsrZWhpTHltaE9VSWJQMjFLSlJvSFkKLS0tIGZ3VTQ0U2wxQThUZitlVWhtai9l
            ZkhVc2dNYW13ZGFOQTREcENndW51ZDgKc35vTW1s+J0mHJSlJ1/FxXHxoVOzLABk
            +cqzW24tEzefjG61pecFcVd9zGyEHR5CXdyhZb7LGGUe8hNFh8tupQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T09:01:23Z"
    mac: ENC[AES256_GCM,data:VdHkkLNW+OwVJDNr/yw3pVLJNq76DES1AWO8ErvwO5iZ1ZgV/lk8QIgJS7TwPmqTCif6rPuxXFJM6cusDtSUnpJdIFeGcR0LlUmYo1CaMEZzZYmeqVINWybgSlYVCw4sbo9D8GloOo7644oTPlora5SiWRQHqkqMXc3M5Zd0Qeo=,iv:cxlJMkdYYWkiMxtspMRfylpsSANObuLnUenXHadPnaw=,tag:JmdJ7P6TiKQQ4ygAETjIxQ==,type:str]
    version: 3.13.0
