apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: paperless-ngx
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:WM3QxfkWnioEslAMDxklq36JvOu8w69RL6E=,iv:ZK580o026Zdjr2v85Le76wxw4TFR4jJ4Ov0Nx0yMB5w=,tag:gUpR5FgfxkcVKZ/gdBPTsw==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:VOufAdgtfDyvDyfif02+x4CbNd7nlf3LISm66KSEXO3OcNOEyuj9PCVZmlLSYce3lKRsy2t8b8CQkw415wTNuA==,iv:qN30NWIsK42eeAWfSR9gG+4IGwMVBG5ABn7VHzlIXl4=,tag:BOdVeXbLn+kEW4uwTrk8ow==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYlBpSnZoMU9HM0svOFhY
            ZEwvckhMQ0IzYm8rMFBvTVlUc0JxNzZ0eFFRCmtLQndFT2JVSWl0K2JveTFvM3d1
            aTVRSmFvOEVHMW9IYlRQS0VhUFpPd0kKLS0tIENmNUdibUlxQTZUbExFdTZCWXh0
            MEFQVno0b3pTajBDTHVkVWVjQWprejAKkyIWGbswwEWO6xeWTOsDQ0zliW1+1dlt
            hfk5zth6zAkg/YiKtouTlfZ2wtlGDulPntnzQEGWM6gKL95JOvbEqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:12T/lgomBR4Xze1XMiouZkP4Oheg1wDM331qOShwhnenW8gpGROsMLTNv4E++9KySyw8xPPy0YWLiiJy6J6f/nD3gdCCDXbhb/mswlmocWXpMVrcx/3gMuIRoLvKBvIiBhdYmJd2qAPvXTRccfop+mahWqYlgzsq2w915t+0K98=,iv:o4f5yFEAS9+9odqtU5+qNKAy8oXiu/vivD41Fx2lzKk=,tag:DtPNgAWeMADO9KtZw4lfbg==,type:str]
    version: 3.13.1
