apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: paperless-ngx
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:3dPTndVDyp/RgKYl39da3guUfRaaajxri8Q=,iv:xJmutFiVxsrCm/cKXbnnp/Vb/fCH8eL+5pkF4IQ6urk=,tag:hKtriQ4KymWbIXeXQoq1Sw==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:37UkExkIdnTZNLnv0M+KqGXDHfwfnmyBGs00TL9WF1PMokuKwXqXa12qj97QD55hWAgLWB7xfS8XGo806GHkgA==,iv:Nsfp7NoU6MBWdvATJ2bDZ7l2ABj4dGg08zZ5NV5X9vQ=,tag:65ZTAD3M3AwYbobICpe8cw==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdWJQK3BIZmJ5UFZ1ekN1
            aGZIeUNwV0dWTjF6YXJrOGJ2QTlJcmFNSDA4CnVVY09aSEJkMWR4T1c3ZVd6Z3lX
            N21GSjFINmlnUS85aGM1Y2svcUFzNUkKLS0tIEh3L3pPZWFMRSt1emt2RGxGeGY1
            TzA4UnBNRlIrdmlXcmpHUEd2MVlhWmsK8YGtam+lDDaXU3O0Qa3IcV8sYvweFFuL
            cKyFg2LYoDntr4odYiV6SxkqJJlmxW8Ds3oHMfKrhdufDgWUMPaheQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:QeQ6GQK8djz4/yYpn43He4xO1BKNMHJHXBvqPa2oFrk3GIxD22RJ0Bk4vnOpVFF8vPF/RGrSbSAW51le2BD5CTcyswl6vfC/sGEwl4mKIwpntciszsrSPi/xEWa7naZVwYNMh8iQXgW/IhVfc6y+wXUm+NDvP4bOSMdqC344RJQ=,iv:+5BcPrqUNYgmZvlwc065X/VxFIEapvEoXglk7IqJdHU=,tag:SkR1J5QjcQhUgYffNaxkDQ==,type:str]
    version: 3.13.1
