# CNPG bootstrap for apps/paperless-ngx/postgres.yaml (owner and database: paperless).
apiVersion: v1
kind: Secret
metadata:
    name: paperless-db
    namespace: paperless-ngx
stringData:
    username: paperless
    password: ENC[AES256_GCM,data:/wOcoOW+BLOX6cKO/I+PJbbD5F33ZNwc5cqXJ9dJVaw=,iv:ykb52vPqeczuNNY6HtvMbwNBQkCB1G2QInYH3AjP+I8=,tag:LFC4SCQnn0nuZ90okEOI3A==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGdsdCtEaUFYMjJMWS81
            dVdwQlM1aE5mUGdVRzZvckx0SGJrOFhpTUZ3Ck1rTjVURGNHM1cwekFmOVBXUDJV
            MUFrS20wVXhRR0h5WlVibjhNMFB5dWsKLS0tIE1mNHAvM3hpbmhBSnM1eTUyZE4v
            dzFoTkNUenhEMkZSbnROUy9yRDl1NmcKGbeL7C3jKrdeXK7qAuTf0PLqctzvqGZZ
            qS/T6IxnAStfQu3y5aK32NyS5cegHHz8wFUFZa1bG4l5TthUteRmZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T09:01:23Z"
    mac: ENC[AES256_GCM,data:zHLw4+I/J5SxgAndo+VNBHxBA6/mnoionDBMdUwn2BBbAShp9BtwVZEHxDqCo+rUvWXCSDBCUr4WKErTEbzOpaIE1n0pR+7Ht422mW+us/gOmqmXNhpt3mgcTUrZWPJP5haBWjV5lf2m5Fr6GWAbfop0E/CsKVbGMopOkgOE1/M=,iv:3mt3OB2Po2cKpA7yfXento1yO7pP9HHbuTeXyXNEuYE=,tag:AiO58rNpuIiRjmb5rlJS+w==,type:str]
    version: 3.13.0
