# PeaNUT NUT connection (mounted once into /config/settings.yml via init container).
# Synology: Control Panel → Hardware & Power → UPS → enable network UPS server;
# add this pod’s IP under permitted devices. NUT users: /usr/syno/etc/ups/upsd.users on the NAS.
# https://github.com/Brandawg93/PeaNUT/wiki/YAML-Configuration
apiVersion: v1
kind: Secret
metadata:
    name: peanut
    namespace: peanut
stringData:
    settings.yml: ENC[AES256_GCM,data:amgtYsfUHIu1rN22GhHmgm/B11eFowHtCY1LpsKI1cP+oy5wPQXseinfExQmXxPbxYGpP7rua9+UTiqJQUAaX/rlY8wwiZwI2Jl/+OJi7Czm0AOYgn/l5gdgUWiB63VnsHw=,iv:6C74ljX38vCrwsJBIcCW7sRJ8EyE/WZyyWu44o5Om/s=,tag:FxVqPyQMJ+xP4yAJQrZVDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdkpnTnI0cUlEaUdUbUJm
            eXJ3anRqQmhCZnMrZjBUV3JwWHNUTkUrYkdvClY5emFmRTErUndUM3BybTBUREta
            elB5RGdnbUVaZm41MkZCbG4vZE9pSHcKLS0tIGszUFV2U2ZSLzVlRDNtTUJNOXVH
            NllqUkRYbG53M1ZkdU9HUTE0SFFYUjgKaJKUcmPndvrKWN87ZwGUq8Sl6rANHMNq
            Z3GYdFRv0b+hbssROr53yDD005pFdEEoxVC3gyEXfg7NKRGQdx5ssA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_regex: ^settings\.yml$
    lastmodified: "2026-05-25T15:25:01Z"
    mac: ENC[AES256_GCM,data:KDFZHFICNGcQ9M3ypBuidrUgdDyeJPCab3gzigx5HA09GMin9CB4opINi8NpfRzEiQ6IVrfT0NzRzoB8kVVYMQAMeYCVjR4dBaU4xxSWaBiHbfxA8jqC7GO2Qz1w8B/oOVOxuFggDc+u8pgKB61oUXO312ne25z8wHYyUvhZg8E=,iv:r9bbtzqlgA9ZPEMPklef54LuFy5Ugv6g+xeIsru+M30=,tag:TMXmW4m8b+HcI6oNG510kA==,type:str]
    version: 3.13.0
