# Tube Archivist API token for Plex scanner/agent (Settings → Application → API Token).
# https://github.com/tubearchivist/tubearchivist-plex
apiVersion: v1
kind: Secret
metadata:
    name: plex-tubearchivist-plex
    namespace: plex
stringData:
    TA_URL: http://tubearchivist.tubearchivist.svc.cluster.local:8000
    TA_API_KEY: ENC[AES256_GCM,data:rwo0a0xLQUJUaEIfAyAnJhKVu4vBC8qeD4LjQrrvCcadCL5B1QJeCQ==,iv:p9aOkWEpFiPtDmUCStBquu4KEYytYc9zvBg078fCAV4=,tag:Q2LMOrB71hEEh3rU009fOg==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NlhTbk5aL0tRQ0F5SjVN
            QXlFMkRyRnBFcEpWZ2drTHg0Y2t0TVBzV1FBClpQWHRRMGZITEdDUDVUTStKcVBh
            aklLQ2RkaDA1dUZZaFVWd0xINGNjSUEKLS0tIEMvNmhMOFB6OXhyaVZxVE10TUJ2
            QWpKSHRDSVpsRkExQ0d2UVJLQ0o3VEUKXji4PRBb2VkvzfMKRhd6UwxqnTTie3x/
            JVMH9SHRN9BPnZGYNpZp6sAUIkdZPZmC5wCroo0vSW1mPC2lHOv+xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-06-05T02:24:20Z"
    mac: ENC[AES256_GCM,data:VERY0SjVlbSO23AGcmbnoBqL1Hx0hDbWUbfqbJFvjeN0gXg6bJS2ISw+5qB7ke3959PnmGFKtWnBtZPrGL71xyQH50REnMXLN3SNB7m/dOACvKUd4etAmlEGMelll0SXy2tU/HvsXHrgXhQeFj2LdzE3HtA2pPXf4J955+2iuTM=,iv:mX/xTFw268wsq42yimbyIZH+U8F43wcaKgNb7NinzOE=,tag:u6txzCNfLV5XKK2+4ShVVQ==,type:str]
    version: 3.13.0
