apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: speedtest-tracker
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:blUvN8GgJYY5WL155ZQcbriuuX5P9YYqaG8=,iv:s8odtupAbeduJbP4v2xmWWosaE3nNSb71VgaB1E7Y9E=,tag:TJqB1aBMvTPtbvov0YcJiw==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:xbAM/FNM8o5MDflIXU08x7jZHRigvsb6gX+LSTHyXqKy+veRI36fO8b/ZRYak7FFavxsSkoWnfBvsBD65FkiDA==,iv:wPkclg8xPgOb9tu8HhvNPEpFUaIgoPkZRCk1kEllGDI=,tag:KLhtEZRTKstwiWOck0ysyQ==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxanJ4aTBjajluMFVTQ1I5
            d0lGKzRDeDJ0cnd1L0lEN0ZERXZ3S2FaYlhJCk5hNHVUR0RFQ1psNk45VUF2YkVm
            VDdvNDk2b0REenk4c2IzZ2NwZndjUEkKLS0tIC9oUG01SDBDdFFvdkt1Yng2bDdo
            a1VUOEE4VytDZzBvZldsKzVnc0xvbFkKoRcf4E/OR5IzF6zSyj8h427XtBGz2Wm5
            Ycq3asBFMkEMP+DeDIrn7Y2M/AJMnYQQRLY1GwvtHocwrEpgdiKWhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:zeBQIXH/dO9alHO8vE/rUWXClzQyLO6Y194ZwcVwhyVNesd/TpeSE+m8bWt7tvbsVNe1aOSBeN/oHVjUYod9L2OeBJ56VVj6HGDG7CJrDTkJXEG54TEqj3xxe6NrJMMzD1bgGyKeOmyeRAnMBFYPu+rPwsKdFHTDHutuBDupr2g=,iv:aT3P3p18VnTzEgVdwTZIJ0H6R85Lv5LnvZgbvzpew+g=,tag:nEsJdpvuk89/7KYzIoNOMw==,type:str]
    version: 3.13.1
