# CNPG bootstrap for apps/speedtest-tracker/postgres.yaml (owner: speedtest, database: speedtest_tracker).
apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker-db
    namespace: speedtest-tracker
stringData:
    username: speedtest
    password: ENC[AES256_GCM,data:fapBNj8ap9nsHTkLCNQD/WiWco1SW5VDZeWuatCk1pQ=,iv:YC8hnWEoUgeYjh3ssFrR4RYk0fqpejXDbW5M+h+2zD0=,tag:y9JQxpbHX/ebBD2IN6LpOA==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNTl0RzVWc0lhY2RUK0dT
            L0F4dEJrNEQvVkxpMUgvN3RuRmVJcmc4UlJjCklvMHMvUVV2YzJheUg0b1d3eUx0
            VzZGTHhOTk1jMWIzdW13ckN6UTRCZ0UKLS0tIFhRcnNUSmZXSWxVTURleVMxRzhw
            UElxVDE0MVM0eEVPNHJnU2hpQzFZb0kKBlp2SACGO0AR2WBGtxGGTVhfVRto7llO
            WNkqjoAXw/uhJHOpQqKWQmOj8DfLb54zMW1BpNUiUe2OJQ0XJzKmRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T09:53:55Z"
    mac: ENC[AES256_GCM,data:eEUErv+9iMooLZCoNGbSm+d5BLaJpPRu9pzF6gkAdoT+b5Es8XE91Vt64u7ajTYW4lgKC47A1TL4PQk1RsnLWW4/TAiyfzf+P9mvzeMrOxVdj6XJmMo2gC31gXneDIY5umdeowcJWv4XMl/RGtttxDA7lLe3Skctt9B8pmqVYj0=,iv:uOvosewWVtDIps1OCTb2sgfchHGYZZJkWM5odobqebs=,tag:5K0Af7404I1VfhqrqA3pPA==,type:str]
    version: 3.13.0
