# Speedtest Tracker app secret — Laravel APP_KEY.
apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker
    namespace: speedtest-tracker
stringData:
    APP_KEY: ENC[AES256_GCM,data:AbiMHtziU3PmNXNK3vxidUdtZ0g+uRu7j4c1AZfCZUIYGke1XEz5yHZUJSZAmXc3psPA,iv:eIoVl7GKpwTgtrk+ckKtGudtE/GxOad8qcXdQ1FxP6A=,tag:S5My33I/+MoWvoh327lh0g==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WlFlNGlKdTltUTlQbWdK
            REc2allsc0pLcWxYd0cvYXVjWkZEdGVLWlZVCmNGNlRqK1JWbk1HZlNGZm0yMHBG
            blQ1dUdSU2NWeXZ0TDUrOUN6L2RPSGcKLS0tIHNCTTRmWjBUUExyaTl3TDhXYnYv
            dXFGY25FZ0pXTmUxNjZGZ1dZcUxiWnMKp0HmUBCUGhEP091ZNpQMojrZxAw1Z6br
            qTAL3aSODgdt3OWFWF+AI3aI8Y5K/k94n2nnLu4MYjHBdndgEfTocg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-24T09:53:53Z"
    mac: ENC[AES256_GCM,data:gDnyxPWyiG9aw2zF+hzt7HfKPjpVJ5Yu/NbmaZ5lC7M0+K6MQwycfI3DT4xWTJj5XCEs+O1vht5LHoiqJD9AFBNqT7WBPKsq3no4FpUCkTrYMPr0nnNWYD2DxP2YlXPJgYIZfxrjrL+qeO6KCYGnHcTE4L+nxIuXXdM51Sd2sXA=,iv:4mGR4Tx/DNdtIvrWm+blY0MZq3h6P1SSj++HwrC/i+w=,tag:d9BCnhMGJP5Kz6LH1s1yRQ==,type:str]
    version: 3.13.0
