apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: speedtest-tracker
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:7M9XoJrWoDpq2NLTiC/IRIgj6gj14BWWUz0=,iv:WcQ0+nnfN4PYa1wkT5LGptSzTqfdVABKKI1eu/mAquQ=,tag:FxajfY33AJmU5fQEVXXINw==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:UN7crPeYgdfsh2Xob182G2KS7nvDJrb5FkuFY58Rby1RQC5bm6uriZPlGw5p+eKRed3Pei4OCglK0BR5iwTQGQ==,iv:ORPxxdP8bK28CNpahm3T7CxlXfh7S7vDgx31bQhtfeY=,tag:6CEZMgdtObKNCsb8zWWbDw==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRXJzTkdGNDljNms2aDli
            cXdIZXU3cGhQMkVmTCtRaFp1a1B3VEtIVWxvCmhhMllMbkkrSkc4bjdIcGxBTEpl
            KzdrTmZ3YlBHeEVkL3J3NmltUE9MMGMKLS0tIGZQdnhHUzNtRkJhb2Vra1Z5WC93
            NWpNS05XTG5GbklyaVVpU2pTV0VCd1UKf2rkrx5Az7xOw9yV82TycEKtUjxK6Vlh
            qkOiZB5tzGPxKCDKDV5nuJMJo4vIrP24LajxxKC+yCmHMa3u2Lnu2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:Ks9hrFSWqUu+jV2NNiJHR5DAx8nQBC7VV+zgQ4jwvppAq2ezcF6lXH5E03O2Nkpx827GEwvUwG0un/o4hUwjM+Ivg4ONeHKr7hPWiLoMCq1NKc9ShE9CdqupOCxJfJKKwpfjVYWI73Q8DLuvaUeZPA0ruCMY3/pxXbmh2bvDxVc=,iv:jPir5ujCsoDKmIzWE33osS0RqesFeqszGXwEmrrJ4Dg=,tag:ESPD3fBw8lHoSLeNrvS0EA==,type:str]
    version: 3.13.1
