# `username` must match bootstrap owner in apps/tracearr/postgres.yaml.
# `DB_PASSWORD` must match `password` (Tracearr Helm reads it from this same secret).
apiVersion: v1
kind: Secret
metadata:
    name: tracearr-db
    namespace: tracearr
stringData:
    username: ENC[AES256_GCM,data:1DTIXV83yvc=,iv:A/phhiLgmfO8eSXvlKHKcuiDzteVziIC0VRVjR8csZE=,tag:5AQicHU5Bl7xcJRrANivLw==,type:str] # sops:encrypt
    password: ENC[AES256_GCM,data:DT9rjOpRBlRV0qR5Pt10+FaoxDXj+KTupgdy7yYEXsk=,iv:a60QH0LYoR58llQchehOlKf16MvgYE5e+9kj8QK7tEM=,tag:o84PrFCnwahjFQsdpIz+7g==,type:str] # sops:encrypt
    JWT_SECRET: ENC[AES256_GCM,data:amd0+p0aem2JH+rxPwWHM9uR7LGrUNhNg8dmeIFMRg8nmzcSu7ZTn/JMPdAV0sQ3iwyVYkqNyTCO1KjuDwTkLg==,iv:eHRnjNMLKPn9xtTgQLpxzj/mUXKLRTQknUTalpjjO4Y=,tag:ol0pumuJHPEK949sw+7uxw==,type:str] # sops:encrypt
    COOKIE_SECRET: ENC[AES256_GCM,data:AULSlTu4wlAGHxa8rQAG4h+7o1fpE8XeKGecQfTFo/QigPNABs2xfGjQuwC+vcPLLI8yEfKrJl5sk7vXhXwxQw==,iv:SmAdlJx8iitCELet0Uarw2NbIF2/hA9CSe1NGu05pK4=,tag:7eCFxZ4Sj9v5pnwLb5ngdw==,type:str] # sops:encrypt
    DB_PASSWORD: ENC[AES256_GCM,data:efcjizw+HmHBHkDTlhGOJwM24uSTMWN4oMkSepithOk=,iv:b07sbQ9QAPFgZV3jdVu4c/s215DNwIiyBKmN8Z52uKo=,tag:JZvB9rCTkPGcS8NTR9Vj9w==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q0xwR3dpN1Q3L3BlWFd0
            bmE4Z041Q2p3cFdnd2oyeWFJSXo2dFN3ckZBCk5ZMVd6WHg5SzVxYk04YkttQWhF
            L2JoZDZtRGpBUFpFMFZjalF2VUUzUHcKLS0tIG5jMUNBRlRvalR4U2ZSWTVaamMv
            Q2JhdXJXcFZiNkFQMVBCM2Y2ZCsrS00KpZ/iiij8pPo0RWpIXGzP7Sr37EWv+Rbp
            zwA/6kMSf6xyD6IrwNB2fNbhP7HY/kDqs6/QBJc+eV3akpqh6W/p3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-19T03:51:53Z"
    mac: ENC[AES256_GCM,data:WRTZpdBlNVQ/v2JoyrvE+W0tWdnHm77prTmNBJ9zTTaXeZEgZRNahCdjvqpIi8Bm3Wi4Q25HWjvUd394GqxqoHCy1KuOuqNlMPsP5j0HUsQJ+QUinBsm35ArD40nBLOzWpylzdLBn4NZWoXoBn6sHFpaCPdQURjvs/ta/NVCsDU=,iv:QoAzLI3273KpTSV+JsT82tkFiZKVtW741NvE9cG2SuU=,tag:p2RDLIYioMNKW3sPeHiJow==,type:str]
    version: 3.13.0
