apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: tracearr
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:IuZMH3bjX15MsbdkmYB7Jfz2tFG/r6CtW/8=,iv:8ZxLaIo17YyHR55lwVoIJ0tjCo3zwzmTkr5XB2/ScmA=,tag:9GwaKqsP8lotk9XRUHXpEw==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:wNuZ/ykV9rVuKYgkCqv9S/LU+A/9BUzPXX5ZUoBPTeb9M0yute/UNArZwXpyG80hXtRTBZc39kuinRqbcmEs/w==,iv:rLUyHZBfd/Op6z/Ik8QRIy796IollU02V7snoXwIQSI=,tag:ZDd6Qt5l0d5sjgfXAnpi+w==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NnZ2eHhTYTdFNGdJSjZM
            MlQ2bnQyeTlCU0tDUkdpOWJvaGZnbWhneW1NCkVKWk5pKzl1a0NVTkZLd3lGbmhX
            QVRhY1A2L0pzaWlKK1dTTHA4c0pJZncKLS0tIGEvK29jWVpnYlRhejVCL1plSEFS
            enNjQ2JTN3phQWJ1ZWo4SmJ2eTIrSHMKBA1P5kdai9cDeBJNlNj9/trzrtuIWvBR
            sTYtgUfQHelkpxWKDqyHQOKRkAMrnzM3MNo4kdXiDfrX2OHdLv6vCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-27T03:28:08Z"
    mac: ENC[AES256_GCM,data:R32tknyjQr3nImaCqkzUbNra11F83wHlPJdnARZKWvFddFTBIQ65+IOGoTNxBrjv4Yb+VhOolfhbVLZz/BjRzAJzi3kBrs997py1IctelDPdUai5AxV+GnQK+sdKnifyiHDKfRkKtS+xe0+tFASEVOexAHf4Rff3HPAAMaPe/KI=,iv:dDJs9cBcrA76Hxyqw29LH1kuz1teAt446ZfH9YN21Cw=,tag:vmmZL2tnpO40vSZ0Vcwucg==,type:str]
    version: 3.13.1
