apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: tracearr
    labels:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:dtRnOJpfriqAu22i95lSsOEgS+4ShR30cyg=,iv:GUlt4CnWOsDq2CoB67dxS7qvMyBpaw8RIhA9Z+aLuGk=,tag:KA/Y2tFfw1MHPVJ5npvNAg==,type:str] # sops:encrypt
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:4pG2JQNiB/Uj4DKM+xSfes5pUsvcPQxSveuYHCzjrJ08Ede84ZJUVgAxLW1r0Wy2vQsfmtcJcS/G04GnpFhpwA==,iv:5qbCPmbnk7f+352/Zwat+Zxg8rqA9rDCw+JIw4F6QCk=,tag:fovazJh2rL6P9PfVyXAN/g==,type:str] # sops:encrypt
    REGION: garage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMnNvN3AydlpUUmxWZEsw
            aHNjOVhGOW5ORU9vOWxDakFnc2lGY0s4V0FFCnEwblZlK0RLc1FMczBJcStRYzRu
            dXNjbytpQlpyTDJONGg5OUcyRmtCTVUKLS0tIElsVEFJSEFmb3hFM0NGSXJCN2xX
            K3pNUFA1aUc0SUFhTTRrdzNxZXNsOVkKGjw9kog2AfO9B2Ylg/wgahBudX7kiDwm
            sxfL1NPKpWJnkHvKS0RzyojmfCnThwA6M9Fp00D6tGoMfkDFOraiZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-08-26T13:22:24Z"
    mac: ENC[AES256_GCM,data:tYGPW4tfqPCkeIjmUyPM173zOdHngaMPOuVDUgz2Q9vyrhYWOhws4KX9zh4NvACxCDRSURb1j5bpAxNTJAFlEy4uSxu7My5LbIf4Qe6QBHIdiDx7UszkubvkO59To/WFCSinnD34mZ4QVBGWxfL02yHPTNUwpjEjVk7xkIbnOa0=,iv:I3IvnTQDu8bSSrzpzpzfUq1teZKmuRXnCgf9+z9BaNw=,tag:L6jZNKg4Mj9VW8B9gN+Rpg==,type:str]
    version: 3.13.1
