apiVersion: v1
kind: Secret
metadata:
    name: tubearchivist
    namespace: tubearchivist
stringData:
    ELASTIC_PASSWORD: ENC[AES256_GCM,data:/8xnPdEy6a5diMHnsUwx6kQc4o7RmKK4MUEwUyWZ,iv:jlhqAKu3gs3gPw1IKjzhP9D1MwzNUnGVcItaYe9sHIg=,tag:yr66p9RSSV05+KerntHZfA==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTkNwS0N2NXFRMWVKWEcr
            dTdFQVNEa0NJVm9ZVHA3blFvRVFnMzQ0cUg0CjQyMlBTMnFFMVJabm9GQytUazk4
            SUZNM3pmNnNsa0t1MWhPNDU0NUFyK0UKLS0tIEZaUmF2OWovRTBKdGQvYm9sNXNn
            YmoxYklWYng4VGd5aERlVGlzVmQwc0EKDsk1/BTrEl9xoQ+tFChKbK/QARDHhN0Y
            Znt2r5EFi3mX95pkKMHxXQdp9NNXw8tpPeiBAXdKnUK0RHxBO9zGtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-17T20:17:21Z"
    mac: ENC[AES256_GCM,data:NBwnnOWa4wzq//Nj0fGSD7lw8aHo4kfifA5lF0zTKqJpFUXxY6buPdKOsSIaUqMtFSL1RIODHpJz4zKk0wNmu+URxCMI0PlCdkfXiYEP/ofvhccTUZFo3WeP1gH6sl54uyqqVgAmfzeoHykfEojziOACjgoO9onHxqidOsqQ8xI=,iv:qQuFNI+cjyYqGnbwtZfJeX8MGFjXCuOeZS8WmCTN/aE=,tag:L6LK1OFtoZovPXGLB4WP/g==,type:str]
    version: 3.13.0
