# UniFi Poller — local admin API (Settings → Admins → Local Access), not your UI login.
# UDM/UXG: use https://<controller-ip> without :8443 (see https://unpoller.com/docs/install/configuration/).
apiVersion: v1
kind: Secret
metadata:
    name: unpoller-unifi
    namespace: unpoller
stringData:
    unifi-url: https://unifi.net.ecksd.ee
    unifi-user: unifipoller
    password: ENC[AES256_GCM,data:nm40gQoeHiiiALq9Hv60pcXXGVLqOzBPXbHZL1L5X4w=,iv:BpI7Jo72lGPnzaGHz5skvcQVmr9yNjfP4Lwh/gTUZ0k=,tag:dsodwVRTKj+ifh6pFf5TWA==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS2FwMlF6MVp3QXpCUWZ3
            RXcwNWNkTFZrR3ZCanN2R3dhT0lVbnV0aURrCmtTRGNjd1d6eTUvbW9GN21TQXFX
            Q3Zjd2I5L1ZranJiUCtwcmFPMHJ6ZVEKLS0tIGcrdzkzZXozbm1kcXdTcnRzd24z
            YVk4LzJINlVOQVJZNGhva1pXRmR5a0UKKUJmwFBdfqvsWRtDQ0WqarIL5m/lG9D/
            NeSIx2NPG/L64nqNJgAaJAMkT1MT8EHQgdV7gzjykx+gEEWZjTZ5HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-25T10:26:38Z"
    mac: ENC[AES256_GCM,data:eJ0kWwaxV6YacA/VU6JK4cucZ+IS1q5Ik27N/YL/56U+sc80iFDoMFfZ6R/vuWkZgkR1qUrbLNY4NXy6aaWRdiYzSXfUtVAnJc2TfQokbNiBOSfz3GbScJxlL8Bw6MC39t4CixoHQvJdJZoChbPqQJdlRdkxTJtTbLSg6bO39y0=,iv:pd+lecz3HSKEec4YYjdlqNtWNYdGBWhIe6VLA+Ly1ds=,tag:3p9u5rVN2AhXeSNyUjQ/7w==,type:str]
    version: 3.13.0
