# https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/custom.md
apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway
    namespace: vpn-gateway
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:S/IZg2LYaMHQ,iv:gfIyQKBxBbCwlDV/6Qj2YdyVFXocR8tUxrjR1gHB+hM=,tag:bCGMzvCiqW5OzHXE/uHTuQ==,type:str] # sops:encrypt
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:+0fYo7V8Og==,iv:oVTCqXGA/eqjLEBrnym132wxl4iaUwkgqhSDlfX4EuI=,tag:u77SRrZqB6hWn7SjNukwcw==,type:str] # sops:encrypt
    SERVER_COUNTRIES: ENC[AES256_GCM,data:VM1ZD6zf,iv:FHgaDGx+ucJZL5psv2D9DAl1JpRb845NcrOOaxUulyA=,tag:DPXWY5zFhpKvtC/S34RQKg==,type:str] # sops:encrypt
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:AxaTfKsbb/J1W84e6ubTx3c5Ynm7rsiIVDS24c15bcJLVNf8ynWIqW+IAeY=,iv:Wn+gfItoy1sKqZ61hLV4reRgOddw8pa/JYORXz/9wnI=,tag:wnx4x/Syz9R6aMMvJ9GW4w==,type:str] # sops:encrypt
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:FJHApXENF104k0ZBqoE=,iv:hlJxKIFe6Tr8rE0byHRlN67kJueFeDS8vSClb5v9DcA=,tag:9uQIhhieRQENw/1JnRmDLQ==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6THRBSEkrQ3ljU1I0VUls
            aFcvNnREQU1hbmEzazFDZGMzTmRjTEdpVFFJCmxrQUMwMEZMekZacGpjdHRKWFRv
            K3AzRm8zT1AvUDZ5aUkwQ1RsaXp2UzQKLS0tIHR6UzN3NkRoU1FyenVXUnN0N29w
            b2l0dlR6bHdzNmVSUWJVVDJXc0RKVFEKt0Dy+2g0T4xCzrsI3tNNUrWzEMx8wFXn
            x/Hyt6PsLrJuN6ncTEH6FA16A4eBjxybeQfeOZFvIk7LbAS80IYI6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-05-18T05:38:27Z"
    mac: ENC[AES256_GCM,data:3XKTe/H++s0M9IktwL7n50P/D9gIDptOeK/OCkTMt4cwmZAM11Mni9poJpZN71oUROJqacayxZjLpSkx26UieBmFcbc2PdUtX7hqKOa5FHPeNrmTDFCrfuuF4tzy4PhXdMHlNLi5/GyIUVek5msLFCSxnVNaWWAcJWauQUEIxr8=,iv:OWqyLnCe9c0YPK0uzcbKFl4EFt204Z6J8fb7Z/UvFko=,tag:QZUa+IegG1fr3eMvYk7H8A==,type:str]
    version: 3.13.0
