# CNPG bootstrap for apps/zilean/postgres.yaml (owner and database: zilean).
apiVersion: v1
kind: Secret
metadata:
    name: zilean-db
    namespace: zilean
stringData:
    username: zilean
    password: ENC[AES256_GCM,data:vRIIhFZQntgTDaHeVi3JsHqXoYACXnsG6PchHnistwg=,iv:SkmtDPxUnR7uA6ODS+7pgqb9v+X+EPHGccytBMZf18I=,tag:XfOhFBaVzHlZXpTj9C1JZw==,type:str] # sops:encrypt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibkQ5VXhZRDk1clVaeGFM
            N2IvbHZBQWV0ZkpmdWlubFl3RnZYZzdCRUNFCmJoankyZVBQc1hEQlJDMjZMUkxW
            eDBJUzR2TDZJVWFNQmpzazBFMnNEemMKLS0tIE5RL3JyZEtHTU9zRmVmUlJRUXd4
            eVNTSVdYSUwyYUNkMmZSOThLRUx3dWMKrPSWgf+zlKTACDIRK/e86GxBEEtXySrL
            kpynztp6P+U6G85XfoDRW+LGOfeqvd9GKLipRRv23mMJqjd0pKSabg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19q6ulkl4tzn5dg4gg3kn2l65ptxpz5jzsv9z7lqqz8jflqndw4tqvple7f
    encrypted_comment_regex: sops:encrypt
    lastmodified: "2026-06-19T01:48:27Z"
    mac: ENC[AES256_GCM,data:NVpNyG6MEhWTWBUWvCpKWQ9gxhbR3TOXQ4LrlQVsZAj6vb6FIosTZX+t9N+gOF7oOLTeMxKJxSm1DshEXBcbNfe15T55TLF4eoIOyZ9AGWdBUvdPsJo0mKCtMwckfjHs6y42SC2ruqZT5LUC07CE1FNR14BzPHur/crVCebgZ18=,iv:TrflAQr3XlySfnNnBc6yUI+jsAna0kWvaV4oIkByOcQ=,tag:QTIDToheznMMNp+bVuNG1w==,type:str]
    version: 3.13.1
