apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peanut-config
  namespace: peanut
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 1Gi
