apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zilean

resources:
  - namespace.yaml
  - pvc-data.yaml
  - postgres.yaml
  - httproute.yaml
  - securitypolicy-forward-auth.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
    releaseName: zilean
    namespace: zilean
    valuesFile: values.yaml
