apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zilean-data
  namespace: zilean
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 20Gi
