apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unpoller

resources:
  - namespace.yaml

helmCharts:
  - name: unpoller
    repo: https://unpoller.github.io/helm-chart
    version: 2.11.2-Chart6
    releaseName: unpoller
    namespace: unpoller
    valuesFile: values.yaml

patches:
  - path: deployment-patch.yaml
  - path: podmonitor-patch.yaml
